### ISSUE TITLE
Table reloads when searching [Remote]

### ISSUE THREAD

**Issue by danipralea** [mbrn/material-table#1143] opened 2019-09-30 16:09 UTC
Hello guys and thank you for the amazing library.
I'm having an issue with remote data being loaded - and when I search - the table reloads. Just wanted to ask for help and see if I'm doing anything wrong - but I did disabled pretty much all the options and the data still reloads.

```typescript
<MaterialTable
    title=""
    options={{
      search: true,
      searchFieldAlignment: 'left'
    }}
    onSearchChange= {(searchText: string) => {
      console.log('search text : ', searchText);
    }}
    tableRef={tableRef}
    components={{
      Toolbar: props => (
        <>
          <MTableToolbar {...props} />
          {isAddingClient && <AddClient cancel={() => setIsAddingClient(false)} success={refresh}/>}
        </>
      ),
    }}
    columns={[
      { title: 'First Name', field: 'firstName' },
      { title: 'Last Name', field: 'lastName' },
      { title: 'Email', field: 'email' },
      { title: 'Website', field: 'website', disableClick: true },
      { title: 'Role', field: 'role', disableClick: true }
    ]}
    data={query => new Promise((resolve, reject) => {
      axios.get(`/clients`)
        .then(response => {
          console.log(new Date().toISOString(), 'fetched clients : ', response.data);
          resolve({
            data: response.data,
            page: 0,
            totalCount: response.data.length,
          });
        })
        .catch(error => {
          console.log('fetching clients error : ', error);
          toast.error('There was an error trying to fetch clients');
          reject(error);
        })
    })}
    editable={{
      onRowUpdate: (newData: Client, oldData) => {
        return axios.patch(`/clients/${newData.id}`, newData)
          .then(_ => {
            toast.success('Client updated!');
          })
          .catch(_ => {
            toast.error('An error occured. Client wasn\'t updated');
          });
      },
      onRowDelete: (client: Client) => axios.delete(`/clients/${client.id}`)
        .then(_ => {
          toast.success('Client deleted!');
        })
        .catch(_ => {
          toast.error('An error occured. Client wasn\'t deleted');
        })
    }}
  />
```

**Comment by jayarjo** [comment] 2019-10-07 10:32
Might be a bug. Have you found a reason?

**Comment by danipralea** [comment] 2019-10-07 10:36
@jayarjo not really

**Comment by jayarjo** [comment] 2019-10-07 18:21
Ah... I actually misunderstood your question. Reloading in the case of search is expected for remote data, because it queries the same endpoint with a keyword. So what exactly would you expect it to do instead?

**Comment by jazzdragon** [comment] 2020-01-15 23:51
@jayarjo I think the issue is that the filters, search and pageSize reset on those reloads. Might be a duplicate of https://github.com/mbrn/material-table/issues/1265

**Closed** 2020-07-07 22:44 UTC
Labels: waiting for author, wontfix
