### ISSUE TITLE
material-table modifies global styles

### ISSUE THREAD

**Issue by Foosballfan** [mbrn/material-table#513] opened 2019-04-26 10:07 UTC
**Describe the bug**
When material-table is on screen it modifies the global styles which cause the material-ui menu drawer and more to render incorrectly.

This is only since upgrading from 1.18 to 1.32

**To Reproduce**
1) Run a site with a material ui menu drawer (https://material-ui.com/demos/drawers/#mini-variant-drawer) 
2) Load a material-table instance in the main view

**Expected behavior**
Material-table does not affect components outside of it's own scope.

**Screenshots**
Look at drawer and back button rendering

<img width="500" alt="Screenshot 2019-04-26 at 11 00 58" src="https://user-images.githubusercontent.com/15104463/56800399-d001f500-6812-11e9-8f57-bbc54af8837a.png">
<img width="500" alt="Screenshot 2019-04-26 at 11 01 23" src="https://user-images.githubusercontent.com/15104463/56800420-dabc8a00-6812-11e9-92b9-1a99b34ef807.png">

<img width="500" alt="Screenshot 2019-04-26 at 11 01 45" src="https://user-images.githubusercontent.com/15104463/56800409-d4c6a900-6812-11e9-96a6-0133c9388161.png">
<img width="500" alt="Screenshot 2019-04-26 at 11 02 13" src="https://user-images.githubusercontent.com/15104463/56800415-d85a3000-6812-11e9-9299-10507d80a261.png">

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] OSX + Windows
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] latest

**Comment by artanisdesign** [comment] 2019-04-30 15:33
Experienced similar issue..

**Comment by mbrn** [comment] 2019-05-01 19:49
I will test this case asap.

**Comment by mbrn** [comment] 2019-05-04 08:53
Hi @Foosballfan , @artanisdesign ,

I could not find any problem with drawer and MT. Can you check this sandbox please? https://codesandbox.io/embed/71z24v9k81

**Comment by mbrn** [comment] 2019-05-04 08:57
I am closing this issue. You can reopen if you need.

**Comment by artanisdesign** [comment] 2019-05-06 08:41
Hi @mbrn ! Thanks for looking into this.

What i meant by similar issue is that, it seems somehow the module affects the styles of other components out of its scope. 

Let me add 2 screenshots: 
![Screenshot 2019-05-06 at 10 34 36](https://user-images.githubusercontent.com/1002099/57214654-ee25dd00-6fea-11e9-81ef-834d8c932172.png)
![Screenshot 2019-05-06 at 10 34 42](https://user-images.githubusercontent.com/1002099/57214658-f0883700-6fea-11e9-9ca4-79f65475e2e0.png)

The 1st is on first load, you can see somehow extra shadows appeared (under appbar for example). If i click away to an other page, then come back it all works okay, so its something on first load and only in production build. This only happens on  the page where i use material-table, if i remove it, all good.

**Comment by mbrn** [comment] 2019-05-06 08:43
Hi @artanisdesign ,

I could not find problem. Can you create a sandbox to reproduce case, please? I want to play on it

**Comment by artanisdesign** [comment] 2019-05-06 08:45
Hi @mbrn 
Will try to create one later on

**Comment by Foosballfan** [comment] 2019-05-06 10:48
A potential factor is that I'm using material-ui/styles (https://material-ui.com/css-in-js/basics/).

Tomorrow I will be able to spend some time working on this issue.

**Comment by artanisdesign** [comment] 2019-05-06 10:56
Hi again! @mbrn 

So here is what i found.. i noticed in production i got class collision.. 
I believe your module uses the same class generator (jss ) as material-ui, and since the counter starts at 0 on both, we can end up with collissions.. 

Once i changed the class prefix in my project [see link](https://next.material-ui.com/css-in-js/api/#creategenerateclassname-options-class-name-generator) its all fine in production. 
You can see the generated classes on the next image. I use "sm" prefix, and you use the built in "jss" prefix, previously both where jss, and in some cases unfortunately got collision. You might wanna have your prefix in the future.

![Uploading Screenshot 2019-05-06 at 12.50.32.png…]()

regards

**Comment by mbrn** [comment] 2019-05-06 11:25
I will take a look at it.

**Comment by Foosballfan** [comment] 2019-05-09 09:34
@mbrn do you need any more info for this bug?

**Comment by mbrn** [comment] 2019-05-12 16:45
> @mbrn do you need any more info for this bug?

i need just time :)

**Comment by Foosballfan** [comment] 2019-05-20 08:12
For anyone experiencing this issue, here is how I prevented it:

```
// top of file 
import { StylesProvider, createGenerateClassName } from '@material-ui/styles';
const generateClassName = createGenerateClassName({
  productionPrefix: 'mt',
  seed: 'mt'
});

// in component
  return (
    <StylesProvider generateClassName={generateClassName}>
      <MaterialTable
       ...
      />
    </StylesProvider>
  );
```

**Comment by mbrn** [comment] 2019-05-26 12:24
> For anyone experiencing this issue, here is how I prevented it:
> 
> ```
> // top of file 
> import { StylesProvider, createGenerateClassName } from '@material-ui/styles';
> const generateClassName = createGenerateClassName({
>   productionPrefix: 'mt',
>   seed: 'mt'
> });
> 
> // in component
>   return (
>     <StylesProvider generateClassName={generateClassName}>
>       <MaterialTable
>        ...
>       />
>     </StylesProvider>
>   );
> ```

This is the solution.

**Comment by SreejithNS** [comment] 2019-05-30 08:47
`// top of file 
import { StylesProvider, createGenerateClassName } from '@material-ui/styles';
const generateClassName = createGenerateClassName({
  productionPrefix: 'mt',
  seed: 'mt'
});

// in component
  return (
    <StylesProvider generateClassName={generateClassName}>
      <MaterialTable
       ...
      />
    </StylesProvider>
  );`

I'm using material-table in many components of my project. Please merge this solution with the next update in such a way that doesn't change the global theme.

**Comment by lucifer1004** [comment] 2019-06-11 05:56
The solution does not work for me 

> For anyone experiencing this issue, here is how I prevented it:
> 
> ```
> // top of file 
> import { StylesProvider, createGenerateClassName } from '@material-ui/styles';
> const generateClassName = createGenerateClassName({
>   productionPrefix: 'mt',
>   seed: 'mt'
> });
> 
> // in component
>   return (
>     <StylesProvider generateClassName={generateClassName}>
>       <MaterialTable
>        ...
>       />
>     </StylesProvider>
>   );
> ```

**Comment by lucifer1004** [comment] 2019-06-11 14:19
Actually, this solution works for `material-table <= 1.36.0`.

For `material-table >= 1.37.0`, the issue is more likely to be #667 instead of this one, which cannot be solved by the solution provided here.

**Comment by jason050196** [comment] 2019-06-12 11:05
Hi @lucifer1004 , I have encountered a similar issue, I found it changed the order of classes.
E.g. I used a <Fab />, after rendering the <MaterialTable/>, the <Fab/> changed its color and shape(border: 0)

Second is I found the performance issue after rendering the <MaterialTable/>

Thanks @mbrn  and appreciate for the hard work and please advise:)

**Comment by indunie** [comment] 2019-06-18 12:08
Hi,
the above solution does not work for "material-table": "^1.39.2".
can you please suggest any other solution. @mbrn 
Thanks

**Closed** 2020-06-30 15:40 UTC
Labels: bug, wontfix

**Comment by PhilMcLachlan** [comment] 2020-07-03 15:05
I am having a conflict of .jss classes from material-table with material-ui's Radio buttons.  The radio buttons are not rendered correctly.  When I remove the table from my UI, the radio buttons render correctly.  lucifer1004's solution won't work for me, because it is not my own library that conflicts with material-table, it is material-ui that conflicts.  Consequently, if material-table used lucifer1004's approach of using StylesProvider above, then I would guess this would solve the problem.
