### ISSUE TITLE
When i add onRowAdd for adding a new row to the table, it throws "TypeError: e.props.onBulkEditRowChanged is not a function"

### ISSUE THREAD

**Issue by sampathkatari** [mbrn/material-table#2276] opened 2020-08-05 07:18 UTC
This issue is also reproducible in the examples provided in the docs.
https://material-table.com/#/docs/features/editable
Expand - Editable Example - Click on plus icon and try adding value to the input fields.

**Comment by eyalgo-investing** [comment] 2020-08-05 07:57
Same, started to experience that few minutes ago after working with an already working table in production for a while...

**Comment by yinchen618** [comment] 2020-08-05 09:00
+1 same issue.

**Comment by LeComptoirDesPharmacies** [comment] 2020-08-05 10:19
+1

**Comment by tinesolbakken** [comment] 2020-08-05 10:51
+1

**Comment by HarishReddyCH** [comment] 2020-08-05 12:32
Same Issue  :(

![Screenshot (231)](https://user-images.githubusercontent.com/65658459/89413050-c1102f00-d745-11ea-8b44-7bc8014d72ca.png)

**Comment by dragan-novakovic** [comment] 2020-08-05 12:47
+1

**Comment by ssurba** [comment] 2020-08-05 14:36
+1 Same issue. And appears in documentation too.
![image](https://user-images.githubusercontent.com/10908064/89425834-bd76ab00-d739-11ea-9637-f7177edbcd0c.png)

**Comment by ssurba** [comment] 2020-08-05 15:03
Duplicate of #2269.

**Comment by mohsinxx365** [comment] 2020-08-06 04:41
Same Issue here aswell

**Comment by akashsrivastava-php** [comment] 2020-08-08 15:32
I am also facing same issue.

**Comment by zipzapp** [comment] 2020-08-10 16:56
+1 this is an issue

**Comment by atosh502** [comment] 2020-08-10 17:34
+1

**Comment by bjj951** [comment] 2020-08-12 04:20
+1 specific to 1.68.0, switching to 1.67.1 solves it unless you need the bulk update feature.

**Closed** 2020-08-16 16:13 UTC
Labels: bug

**Comment by gxtaillon** [comment] 2020-09-22 20:57
@mbrn I'm not sure if there has been a regression but the error is occurring in the demo when trying to edit any column.

https://material-table.com/#/docs/features/editable

![image](https://user-images.githubusercontent.com/567119/93936528-51a1cf00-fcf4-11ea-9160-5d0bc47f60ae.png)


```
TypeError: e.props.onBulkEditRowChanged is not a function
    at a.<anonymous> (m-table-edit-row.js:218)
    at no (react-dom.production.min.js:193)
    at ao (react-dom.production.min.js:193)
    at Ho (react-dom.production.min.js:216)
    at qo (react-dom.production.min.js:220)
    at react-dom.production.min.js:250
    at Object.t.unstable_runWithPriority (scheduler.production.min.js:18)
    at Ad (react-dom.production.min.js:250)
    at Dd (react-dom.production.min.js:249)
    at Nd (react-dom.production.min.js:248)
```

**Comment by deivid-01** [comment] 2021-07-17 01:44
Same Issue, version 1.68.0

**Comment by deivid-01** [comment] 2021-07-17 01:49
> .67.1

It works perfectly!

**Comment by deivid-01** [comment] 2021-07-17 01:50
> +1 specific to 1.68.0, switching to 1.67.1 solves it unless you need the bulk update feature.

It works perfectly!
