### ISSUE TITLE
Tooltip causing flickering bug in pagination buttons / Request to have option to disable tooltips

### ISSUE THREAD

**Issue by LJEsp** [mbrn/material-table#126] opened 2018-12-21 14:13 UTC
I believe the tooltip is causing a flickering bug in the pagination buttons. It would be nice if there's an option to disable tooltips.

Video link: https://youtu.be/ouzkjLeaiJk

**Comment by mbrn** [comment] 2018-12-22 11:08
Hi @LJEsp,

I could not reproduce this case. But i think this is related with material-ui's tooltip component. 

What is your envoirenment (browser, os, etc...)

**Comment by LJEsp** [comment] 2018-12-22 13:09
I've updated material-ui from 3.6 to 3.7 and the bug was gone. The changelog describes a fix for this. Thanks!

**Comment by LJEsp** [comment] 2018-12-22 13:38
But this error now appears..
![image](https://user-images.githubusercontent.com/36854142/50375017-e9f7b500-0631-11e9-9034-00909ec719b6.png)

**Comment by mbrn** [comment] 2018-12-22 18:35
Ok. This error will be resolved with next release. Thanks to developer of #124  :)

**Closed by mbrn** 2018-12-22 18:35 UTC
Labels: bug
