### ISSUE TITLE
Override a single filter instead of FilterRow

### ISSUE THREAD

**Issue by nbrustein** [mbrn/material-table#1072] opened 2019-09-05 18:55 UTC
**Is your feature request related to a problem? Please describe.**
When I want to provide a custom component to use for filtering, it seems that I have to implement the entire FilterRow.

**Describe the solution you'd like**
Support a `filterComponent` property in the column definition.  If defined, this component would replace the component that is used for filtering at the top of each column.

**Comment by gabrielgian** [comment] 2019-09-16 12:53
+1

Since there is a editComponent prop, I think it would make sense to add filterComponent in coluns definition by following the same pattern.

**Comment by jayarjo** [comment] 2019-10-08 08:21
Would it help if `FilterRow` was exported and you could import and override it? We are hesitant of adding any additional props for everything - config is already kind of too big.

**Comment by janderson215** [comment] 2019-12-07 15:30
I recognize that I didn't start this thread, so I hope I'm not posting out of turn, but it's been a while so I figure I'll add my 2 cents to get this issue moving. Yes, that is a valid way to solve it and I agree that the config is large, but IMO since there are multiple `Filter` types (`lookup`, `input`, etc…), the `component` prop override could get very messy when it comes to configuring the different filter types when compared to defining them as needed in the `columns` prop. 

My use case is that I'm trying to build a very dense table for a tiny component, but I can't remove the margin-top of 16px from the filter `lookup` component. Additionally, the filter `input` bottom line is not aligned with the `lookup` bottom line. 

This might be a duplicate of #379

**Closed** 2020-06-30 13:40 UTC
Labels: enhancement, waiting for author, wontfix
