### ISSUE TITLE
Detail Panel Collapse When update rowData

### ISSUE THREAD

**Issue by Spartano** [mbrn/material-table#1021] opened 2019-08-23 14:08 UTC
**Is your feature request related to a problem? Please describe.**
every time i update the rowData all of my detail panel auto close.

**Describe the solution you'd like**
I would like that my detail panel woul be able to stay open on the arriving of new rowData

**Comment by Penlane** [comment] 2019-10-08 10:14
+1, it would be awesome if the rendering could be separated between row and detailPanel.
In the meantime, is there any workaround, like using a collapse component?

**Comment by Quanga** [comment] 2019-10-16 08:56
Same issue, would appreciate any workaround or ideas

**Comment by VicenteQueiroz** [comment] 2019-10-23 11:43
Also have the same problem. What I did was to mutate the state directly of the input inside my detailPanel. This isn't a good React practice though

**Comment by VicenteQueiroz** [comment] 2019-10-24 12:23
Of course @rkulinski. In my parent component i have the state with all the data for the table. My table has a detail panel with an input. The onChange handler function sets the data to the state in the parent component. Now every time I did an input change the detail panel closed
Now in the handler function instead of doing the classic:
`
const {inputData} = this.state
inputData = evt.target.value
this.setState({inputData})
`
I mutate the state directly:
`
const inputData = this.state.inputData
inputData = evt.target.value
this.setState({inputData})
`
And this fixed that issue of closing the panel. Let me know if this worked for you as well

**Comment by rkulinski** [comment] 2019-10-29 16:30
Hmm. I haven't tried it yet. But it seems odd. The only difference I can see is that first code sample uses destructing assignment and the other one not. I don't see how does it change anything. Didn't you mean to write `this.state.inputData = inputData`?

**Comment by quentinwendegass** [comment] 2019-12-30 13:53
Has nobody found a workaround for that issue yet?

**Comment by amir-aimco** [comment] 2020-01-06 21:44
I have the same issue. This feature could be a great addition to material-table.

**Comment by chrisLoPresti** [comment] 2020-01-11 15:40
if you could add an 'expanded' prop like material ui does for their expansion panels that'd be great. 

that way when we change the state we can at-least hold onto a list of panels that should be expanded.

**Comment by amir-aimco** [comment] 2020-01-14 16:56
I have found a temporary half workaround in my case. Depending on how you manage the data, you might be able to use shouldComponentUpdate to at least do not let the detail panel collapse if data has not changed.

**Comment by lukavida** [comment] 2020-02-13 22:22
A workaround for this:

Let's say you have the following data that you want to show in the table. You keep the data in the state, it is being updated, but you don't want details panels to collapse when the data is updated (when `size` on object with uid 'b' changes from 3 to 4):  

```
[
{uid: "a", size: 2, ...},
{uid: "b", size: 3, ...},
{uid: "c", size: 2, ...},
...
]
```

**Solution: Detailed map + Simple array**

Add a Map to the state, use `uid` as map keys and push respective values to the map.

```
"a" => {uid: "a", size: 2, ...},
"b" => {uid: , size: 3, ...},
"c" => {uid: , size: 2, ...},
```

Create a separate array in the state that will only contain `uid` values:
```
this.setState({
    array: Array.from(this.state.map.keys())
}); // ["a", "b", "c"]
```
Pass `this.state.array` as a data source to MaterialTable.

The array doesn't contain all the data (just the `uid`). In the table render function, take the `uid` and get the actual row data from the map:
```
render: rowData => {
    let actualRowData = this.state.map.get(rowData.uid);
    ...
    // use actualRowData.size
    ...
}
```

With this new setup, when you do any changes to the original data in the state, which is stored in the Map, the array that is passed to the table won't update, and panels won't collapse.

**Comment by gtupak** [comment] 2020-02-20 23:28
@lukavida This could definitely be a solution, but it still doesn't seem right to do all that work for such a simple task. Like @chrisLoPresti said, this would be a great addition to the current library.

**Comment by lukavida** [comment] 2020-02-21 05:51
@gtupak well of course it would.

But those that desperately need the solution (like I was) will be thankful that someone invested time researching and providing a detailed explanation of a workaround.

**Comment by jonathanthec** [comment] 2020-03-19 21:41
Also facing the same issue. Pumping this up - this would be a great feature to have.

**Comment by cyrusDAVO** [comment] 2020-03-31 16:30
Same issue here

**Comment by Domino987** [comment] 2020-06-02 10:32
The problem is, that material-table mutates the objects and adds a tableData object to the objects passed in the data prop. This tableData object contains stuff like id and expanded. By updating the data, this tableData object is lost and a new one will be added, but the default is collapsed.

So to persist the expansion, you need to keep track of this tableData object. This is connected to an underlying problem with the mutation and will be fix in future releases, once the issues and PRs are taken care of as far as I know.

To keep track of them you could to it like this:
```
const [data,setData]= React.useState([MY_ITEMS]);

const updateData = (index, newValue) => {
    setData(prevData => {
         const newData = prevData.map(d => ({...d}));
         newData[index].name = newValue;
         return newData;
    });
}

// To manually expand a row, do it like this:
const expendRow = (index) => {
       setData(prevData => {
         const newData = prevData.map(d => ({...d}));
         newData[index].tableData.expanded = true;
         return newData;
    });
     }

return <MaterialTable data={data} .../>
```

**Comment by andrescuco** [comment] 2020-09-01 03:20
Bumping, one of the most important open issues currently imo.

**Comment by iltumio** [comment] 2020-11-24 21:47
I wrapped material table and I tracked opened panels with ref. I know that it's not the best solution, but at least it works

```
import React, { useEffect, useRef } from "react"
import MaterialTable from "material-table"

export function CustomMaterialTable(props) {
    const tableRef = useRef()
    const openedPanels = useRef({})
    const oldFunction = useRef()

    useEffect(() => {
        if (!oldFunction.current) {
            oldFunction.current = tableRef.current?.onToggleDetailPanel
        }

        if (oldFunction.current === tableRef.current?.onToggleDetailPanel) {
            tableRef.current.onToggleDetailPanel = (path, render) => {
                if (
                    tableRef.current.props.data[path[0]].tableData
                        .showDetailPanel
                ) {
                    delete openedPanels.current[path[0]]
                } else {
                    openedPanels.current = {
                        ...openedPanels.current,
                        [path[0]]: true,
                    }
                }

                oldFunction.current(path, render)
            }
        }
    }, [tableRef])

    return (
        <MaterialTable
            tableRef={tableRef}
            {...props}
            data={
                props.data?.map((d, i) => ({
                    ...d,
                    tableData: {
                        showDetailPanel: openedPanels.current[i]
                            ? props.detailPanel
                            : null,
                    },
                })) || []
            }
        />
    )
}

```

**Comment by PhilObi** [comment] 2021-01-22 19:56
After about 2 days of madness, I figured out what was causing this issue at least for me anyway, but I have a hunch it's what's causing it for you guys as well. The problem was when I updated the row data by making a mutation, material-table checked my cache with my current table data and refreshed if they were different. I fixed this problem by making the table cacheless. This should prevent it from closing the detail panel. Good Luck!

**Comment by henry25225** [comment] 2021-02-16 17:31
Even props.data is updated, detailPanel won't collapse
`
const [detailVisibles, setDetailVisibles] = useState<>({});

  const renderDetailPanel = (rowData) => <DetailPanel data={rowData} />;

  const data = useMemo(
    () =>
      props.data.map((rowData) => ({
        ...rowData,
        tableData: detailVisibles[rowData.id]
          ? {
              showDetailPanel: renderDetailPanel,
            }
          : {},
      })) ?? [],
    [props.data, detailVisibles],
  );

  return (
    <MaterialTable
      columns={columns}
      data={data}
      onRowClick={(event, rowData) =>
        setDetailVisibles({ ...detailVisibles, [rowData.id]: !detailVisibles[rowData.id] })
      }
    />
  );
`

**Comment by llezhava** [comment] 2021-02-24 07:01
Thanks, @iltumio you saved my day!
However, I had issue when table was sorted & filtered, because `path[0]` is no longer reliable identifier. I assumed, that each item has it's id and used it as an identifier.

```
export function CustomMaterialTable<T extends {}>(props: MaterialTableProps<T>) {
  const tableRef = useRef<any>();
  const openedPanels = useRef<Set<any>>(new Set());
  const oldFunction = useRef<any>();

  useEffect(() => {
    if (!oldFunction.current) {
      oldFunction.current = tableRef.current?.onToggleDetailPanel;
    }

    if (oldFunction.current === tableRef.current?.onToggleDetailPanel) {
      tableRef.current.onToggleDetailPanel = (path: any[], render: any) => {
        oldFunction.current(path, render);

        openedPanels.current.clear();

        tableRef.current.props.data?.forEach((item: any) => {
          if (item.tableData.showDetailPanel) {
            openedPanels.current.add(item.id);
          }
        });
      };
    }
  }, [tableRef]);

  return (
    <MaterialTable<T>
      tableRef={tableRef}
      {...props}
      data={
        (props.data as Array<any>)?.map(d => {
          return {
            ...d,
            tableData: {
              showDetailPanel: openedPanels.current.has(d.id) ? props.detailPanel : null,
            },
          };
        }) || []
      }
    />
  );
}
```

**Comment by krishnaUIDev** [comment] 2021-03-03 02:57
any update regarding this? I am facing the same issue. When I try to edit the detail panel is closing automatically.

**Comment by omergal99** [comment] 2021-05-05 12:30
I tried the 3 refs solution.
I can tell that use the 3 ref it's really heavy solution, affected performance when have more "logic" inside each detail panel.

**Comment by Domino987** [comment] 2021-05-05 20:37
Since this is not longer supported, please upgrade to @material-table/core

**Closed** 2021-08-11 03:34 UTC
Labels: enhancement, help wanted, wontfix

**Comment by IsmoilAnvarov** [comment] 2021-11-22 10:16
iltumio Thank you !
