### ISSUE TITLE
endless loading/spinning when using function for data (remote data)

### ISSUE THREAD

**Issue by hbinkle** [mbrn/material-table#1429] opened 2019-12-09 14:04 UTC
the table rerenders/spinns endless when using a fuction for data instaed of a preloaded object.
- Not matter if I call resolve or reject.

https://codesandbox.io/s/material-demo-yvqym?fontsize=14&hidenavigation=1&theme=dark

**Comment by SvenNussgruber** [comment] 2020-01-08 18:23
In your sandbox the query string is the URL to your sandbox. Did you mean to query an API endpoint instead?

**Comment by hbinkle** [comment] 2020-01-09 12:03
> In your sandbox the query string is the URL to your sandbox. Did you mean to query an API endpoint instead?

Right, it should be an API endpoint when the code is really used. But in the demo case it does't matter because the response is not used. I could also have used "http://www.google.com". It simply needs to be a successfull fetch to demonstrate.

**Comment by pjshu** [comment] 2020-01-19 07:42
same problem

**Comment by cinnabarcaracal** [comment] 2020-01-20 05:17
We're getting this same issue in our project. The table is given a function that returns a promise, and it can fetch data normally just fine. But if the promise fails, the table `isLoading` state stays as `true`.

I can tell the promise is failing because it will execute a `.catch` if I put one in there

**Comment by cinnabarcaracal** [comment] 2020-01-20 05:26
I think the problem is in the `onQueryChange` function in `material-table.js`.

Potential solution:
```
onQueryChange = (query, callback) => {
  query = { ...this.state.query, ...query };

  this.setState({ isLoading: true }, () => {
    this.props
      .data(query)
      .then(result => {
        query.totalCount = result.totalCount;
        query.page = result.page;
        this.dataManager.setData(result.data);
        this.setState(
          {
            isLoading: false,
            ...this.dataManager.getRenderState(),
            query,
          },
          () => {
            callback && callback();
          },
        );
      })
      .catch(reason => {
        this.setState({ isLoading: false });
      });
  });
};
```

**Comment by restaadiputra** [comment] 2020-01-28 12:57
Is there any news about this? I am having the same issue and as for my current solution is accessing the table ref in my .catch and call the setState manually to stop the loading animation, 

`
.catch(error => {
        tableRef.current.setState({
          isLoading: false
        });
        console.log('ERROR ', error);
});
`

**Comment by cinnabarcaracal** [comment] 2020-06-30 22:18
Please don't close this issue

**Closed** 2020-10-06 00:28 UTC
Labels: wontfix
