### ISSUE TITLE
Conditional disabled stopped working from version 1.54.0

### ISSUE THREAD

**Issue by kkateli** [mbrn/material-table#1459] opened 2019-12-18 20:26 UTC
**Describe the bug**
Refers to Material Table documentation Actions-> Conditionals Actions Example . Disabled property stopped working in 1.54.0 onwards. Even set disabled to true, no button is disabled. 

<img width="780" alt="Screen Shot 2019-12-19 at 9 24 22 AM" src="https://user-images.githubusercontent.com/39331184/71120525-78047c80-2241-11ea-8253-297fd8521b29.png">

**Comment by Eplumecocq** [comment] 2019-12-19 15:37
Possible duplicate of #1326

**Closed** 2020-06-30 23:42 UTC
Labels: wontfix
