### ISSUE TITLE
MUI - Failed prop type: Invalid prop 

### ISSUE THREAD

**Issue by rommelmamedov** [mbrn/material-table#1317] opened 2019-11-11 19:33 UTC
[This line](https://github.com/mbrn/material-table/blob/536d73e4a4b004df38fe0df2048e8355fe514d47/src/components/m-table-edit-row.js#L35
) in m-table-edit.row.js 
**Screenshots**

<img width="1187" alt="Screen Shot 2019-11-11 at 23 31 59" src="https://user-images.githubusercontent.com/38986496/68614996-92796680-04db-11ea-9ffe-dc812539e8ac.png">

**Comment by atjeff** [comment] 2019-11-11 20:13
Duplicate of https://github.com/mbrn/material-table/issues/1293

**Closed** 2019-11-12 07:00 UTC
