### ISSUE TITLE
Lookup popup doesn't disappear during loading remote data

### ISSUE THREAD

**Issue by MohammedSaberMohammed** [mbrn/material-table#1627] opened 2020-02-09 09:11 UTC
**Bug Description**
when i'm trying to select a value from table lookup and when the debounce interval finished the table loader appears but the lookup popup still appears and its position is above loader unless i click on any place

**Steps to reproduce the behavior:**
1. load remote data
2. select a value from a lookup in the table and don't do any click 
3. you will notice the table loader appears
4. also you will see the lookup popup above the loader unless you clicked away

**Expected behavior**
when i choose from lookup and when the debounce interval is finished the lookup popup should disappear 

**Screenshots**
![lookup above loader](https://user-images.githubusercontent.com/19964514/74099430-61392280-4b2c-11ea-9700-14ae13bdaac2.gif)

thanks in advance

**Comment by Domino987** [comment] 2020-02-11 10:14
I cannot reproduce this. Can you share a codesandbox or your code?

**Comment by MohammedSaberMohammed** [comment] 2020-02-12 06:34
`ss`

**Comment by MohammedSaberMohammed** [comment] 2020-02-12 06:56
@Domino987 try to choose from lookup when select a value and waiting For response you will see that the lookup popup will be above loader and it will not disappear is there is a work around to close it during getting remote data?

**Comment by Domino987** [comment] 2020-02-12 08:37
The loader does not start for me. Can you share your code ? Or reproduce it in a code sandbox?

**Comment by MohammedSaberMohammed** [comment] 2020-02-12 09:09
@Domino987 , oh Sorry i forgot to share the link my mistake, 
here is the link 
https://codesandbox.io/s/popup-above-m-table-loader-06p8k

**Comment by Domino987** [comment] 2020-06-07 14:09
Fixed in #1642

**Closed by Domino987** 2020-06-07 14:09 UTC
