### ISSUE TITLE
Material Table freezes Browser

### ISSUE THREAD

**Issue by Sandy2691** [mbrn/material-table#2451] opened 2020-09-12 10:16 UTC
# Guidelines

- #### Please include a demo of the issue/behavior/question you have

- #### Please try to be as detailed as possible

- #### You may fork one of the following starter templates if you would like:

  - #### [CodeSandbox](https://codesandbox.io/s/material-table-starter-template-xnfpo)
  - #### [StackBlitz](https://stackblitz.com/edit/material-table-starter-template)

**Describe the bug**
Material Table freezes the screen when trying to reload new data. I have an input field and making a service call with that input field and adding the new data to the state(state contains the data supplied to the table). And also for every change in input value Material table is rerendered and it's slowing down the page

**To Reproduce**

1. Enter value in input field
2. Enter search button(Make a service call and update state with newdata)
3. For the 2nd search the browser is becoming slow
4. For the 3rd search the browser completely becomes unresponsive

**Expected behavior**
Material Table should not freeze the screen
**Screenshots**

**Desktop (please complete the following information):**

OS: windows server 2016 standard(64 bit),
Browser:Chrome
Version:85.0.4183.102

**Smartphone (please complete the following information):**

**Additional context**
Using Materiaa Table version 1.62.0

**Comment by DewangS** [comment] 2020-09-13 01:07
please refer to my previous issue **Poor performance. Page gets unresponsive #2433** I found the same problem so as a few others. Till this is resolved, I've moved back to core material-ui table

**Comment by Sandy2691** [comment] 2020-09-15 06:50
Downgraded the package to 1.61.0 and the issue is resolved.

**Comment by arelra** [comment] 2020-09-15 17:41
Also linked #2418 and potentially #2425 

There seems to be a large json objet called `tableData` added to the column data:

https://github.com/mbrn/material-table/issues/2433#issuecomment-690290099

Possibly this has cyclic references, objects are not immutably recreated and parsing enters an infinite loop / memory leak

**Comment by DewangS** [comment] 2020-09-15 22:58
as per someone else it's pretty stable anything below v.1.67.0

**Comment by jonassvalin** [comment] 2020-09-18 08:34
+1 on this issue. Works well when downgrading to 1.67.0

**Comment by tybeck** [comment] 2020-09-21 15:34
This just saved me hours of debugging...Thanks! +1.

**Comment by sujay-gandham-by** [comment] 2020-09-21 15:43
`v1.68.0` works fine for me. Browser freeze occurs when I use `v1.68.1` + the jspdf warning.

**Comment by masbaehr** [comment] 2020-09-21 16:53
> 
> 
> please refer to my previous issue **Poor performance. Page gets unresponsive #2433** I found the same problem so as a few others. Till this is resolved, I've moved back to core material-ui table

As much as i like mbrn/material-table i'm also done with it for now. Will also move back to core material-ui table. Recently this library is giving me nothing but work and problems, and unfortunately pull requests take an eternity to be merged and released to a new version :(

Downgrading is a pretty bad option considering the bugs previous versions had

**Comment by nightwolf-041** [comment] 2020-09-23 10:03
**use v.1.67.0**

**Comment by nightwolf-041** [comment] 2020-09-23 10:05
> Downgraded the package to 1.61.0 and the issue is resolved.

**It works properly in the 1.67.0**

**Comment by ilhamsa1** [comment] 2020-09-25 16:38
I don't really understand. when I put column as a variable and put it outside the react component. my browser always hangs

```
const COLUMNS = [
  {
    title: 'Name',
    field: 'name',
  },
{
    title: 'test',
    field: 'test',
  },
}]
const myTable = () => {
 <MaterialTable
      columns={COLUMNS}
      ...
   />

```
but if I put it directly in the props column it works fine

```
 <MaterialTable
      columns={ [
  {
    title: 'Name',
    field: 'name',
  },
{
    title: 'test',
    field: 'test',
  },
}]
 ...
/>

**Comment by saunlani** [comment] 2020-10-02 13:16
also experiencing this issue when columns are passed to the material-table as props from a parent component.  downgrading to 1.67 has resolve the issue for now.

**Comment by swiftech** [comment] 2020-10-04 03:39
I have 2 routed pages which both contains a material-table, when I switch the 2 pages back and forth by clicking route link, the browser freezes.

Version: 1.69.0
OS: Mac Catalina
Chrome:  v85.0.4183.121

**Comment by chrisbag** [comment] 2020-10-14 17:38
> I have 2 routed pages which both contains a material-table, when I switch the 2 pages back and forth by clicking route link, the browser freezes.

Same on my side with 1.69.1

**Comment by samje** [comment] 2020-10-26 07:53
> I don't really understand. when I put column as a variable and put it outside the react component. my browser always hangs
> 
> ```
> const COLUMNS = [
>   {
>     title: 'Name',
>     field: 'name',
>   },
> {
>     title: 'test',
>     field: 'test',
>   },
> }]
> const myTable = () => {
>  <MaterialTable
>       columns={COLUMNS}
>       ...
>    />
> ```
> 
> but if I put it directly in the props column it works fine, I'm using version v.1.69.0
> 
> ```
>  <MaterialTable
>       columns={ [
>   {
>     title: 'Name',
>     field: 'name',
>   },
> {
>     title: 'test',
>     field: 'test',
>   },
> }]
>  ...
> />
> ```

This fixed the freezing issue for me. 

I have custom filters for data which causes the table to re-render and after few changes to the table the browser tab starts to slow and eventually freeze/crash.

**Comment by lwazevedo** [comment] 2020-11-04 16:55
Hi, 
I have the same problem in both version 1.67 and 1.69. I managed to get around the problem in this way.

`import React, { useMemo } from 'react';
import MaterialTable from 'material-table';

export default function MyComponent () {

  const columns = useMemo(() => [
    {title: 'My Title One', field: 'field_one'},
    {title: 'My Title Second', field: 'field_second'},
  ], [])

  const data = [{
    field_one: 'Any one',
    field_second: 'Any second'
  },
  {
    field_one: 'Any one more',
    field_second: 'Any second more'
  }]

  return (
    <MaterialTable 
      columns={columns}
      data={data}
    />
  )
}`

**Comment by alexdobsom** [comment] 2020-11-10 23:33
> but if I put it directly in the props column it works fine, I'm using version v.1.69.0
> 
> ```
>  <MaterialTable
>       columns={ [
>   {
>     title: 'Name',
>     field: 'name',
>   },
> {
>     title: 'test',
>     field: 'test',
>   },
> }]
>  ...
> />
> ```

this works but it's not optimal :)

**Closed** 2020-11-17 09:04 UTC
Labels: bug

**Comment by yassinejebli** [comment] 2020-11-27 11:32
> I don't really understand. when I put column as a variable and put it outside the react component. my browser always hangs
> 
> ```
> const COLUMNS = [
>   {
>     title: 'Name',
>     field: 'name',
>   },
> {
>     title: 'test',
>     field: 'test',
>   },
> }]
> const myTable = () => {
>  <MaterialTable
>       columns={COLUMNS}
>       ...
>    />
> ```
> 
> but if I put it directly in the props column it works fine, I'm using version v.1.69.0
> 
> ```
>  <MaterialTable
>       columns={ [
>   {
>     title: 'Name',
>     field: 'name',
>   },
> {
>     title: 'test',
>     field: 'test',
>   },
> }]
>  ...
> />
> ```

This works for me as well, but it's weird, I'm not sure why this has anything to do with the issue! the only difference that I can see is the constant (COLUMNS) is declared outside material-table scope.

**Comment by AnimeshTimsina** [comment] 2020-11-29 04:56
It still freezes even when I downgrade to 1.67.0. It works only if I declare columns directly inside the component

**Comment by peacechen** [comment] 2020-12-10 23:10
I was able to narrow this down to PR #2351 by testing using a binary git commit search. That commit is between 1.68.1 and 1.69.0, and is the first one post-1.68.1.  There are many changes in that commit, and I'll need to isolate it further.

![image](https://user-images.githubusercontent.com/6295083/101840930-9c203400-3b0a-11eb-8078-2ab5a89bfbf6.png)

**Comment by DewangS** [comment] 2020-12-10 23:22
@AnimeshTimsina 

That's odd. Mine works fine with 1.67.0 having column declaration separate as an array.

**Comment by peacechen** [comment] 2020-12-11 05:21
Commit 9c32f97d83e9c47c01512331e848176176b0a38a is the culprit (amusingly titled "last" 🤣 ).

The code that triggers this is in data-manager.js:
```
      if (columnDef.tableData.width !== undefined) {
        usedWidth.push(columnDef.tableData.width);
      }
```
https://github.com/mbrn/material-table/blob/master/src/utils/data-manager.js#L89

Reverting this prevents freezing up the browser:
```
      if (columnDef.width !== undefined) {
        usedWidth.push(columnDef.width);
      }
```

Obviously that in itself isn't the root cause. It's triggering other parts of the code that appear to be related to auto sizing.  @mbrn would you provide some insight into how this works?

My app is using remote data and handles the data fetching and sorting API calls. I've tested the API and it's performing properly (it's the first thing I made sure was ok).

**Comment by yehonadav** [comment] 2020-12-12 16:46
what's the status on this? which version should we revert to?

**Comment by VFC-elindgren** [comment] 2020-12-15 21:32
For me I had to revert to 1.65, 1.67 still froze, as others have mentioned I have column definitions defined outside of the component. 

But I've also found a workaround:

```
export const SongTable = ({ songs= [] }: Props) => {
  console.log("songtable");
  return <MaterialTable data={songs} columns={columns()} />;
};

const columns = () => [
  { title: "Title", field: "title" },
  { title: "Orchestra", field: "orchestra" },
  { title: "Singer", field: "singer" },
  { title: "Year", field: "year" },
  { title: "Genre", field: "genre" },
  { title: "Length", field: "length" },
];
```

Since it seems like the only difference in declaring the columns outside the component is whether there's a static references or its an anonymous array, I did it like this, so the array is recreated each render. Not pretty but seems to solve the hanging.

**Comment by yehonadav** [comment] 2020-12-15 22:26
1.68.0 worked for me,
also, i created my columns inside zustand (a state manager), 
so maybe we should check out if creating the columns  inside a state, or inside an object can work around this:

examples:

// this would cause problems
const columns = [
  { title: "Title", field: "title" },
  { title: "Orchestra", field: "orchestra" },
];

// this might work ?
const container = {
  columns: [
    { title: "Title", field: "title" },
    { title: "Orchestra", field: "orchestra" },
  ],
};

**Comment by peacechen** [comment] 2021-01-06 07:28
Unfortunately mbrn is inactive and not merging PR's.  Use the official community fork [@material-table/core](https://github.com/material-table-core/core) instead.

**Comment by Bluefitdev** [comment] 2021-03-31 02:44
I've been trying to fix this issue for the past 4 hours! I thought it was my code. I can confirm that reverting back to `1.67.0` fixed this.

**Comment by ZeeshanAhmadKhalil** [comment] 2021-05-09 11:24
> Downgraded the package to 1.61.0 and the issue is resolved.

I have been looking for ways to optimize `redux` for the last 6 hours! didn't know the problem was with `material table, Thanks!

**Comment by andrei10k** [comment] 2021-05-15 10:36
why is this closed? it's still reproduceable in the latest version

**Comment by Strauteka** [comment] 2021-05-17 15:15
Same with version  "material-table": "^1.69.3" Downgrade to "material-table": "1.65" fixes issue!

**Comment by aphammyriad** [comment] 2021-05-21 23:25
Can confirm this is still happening in 1.69.3

**Comment by hmetgundogdu** [comment] 2021-06-01 11:27
@aphammyriad Yep we can confirm, it happening in 1.69.3

**Comment by MariaDimitrova-CoherentSolutions** [comment] 2021-06-09 11:38
I solve this issue inside the component where I`m using MaterialTable component with:
```
const columns = props.columns.map((column) => {
    return { ...column };
  });
```
```
<MaterialTable
        data={data}
        options={options}
        columns={columns}
        ...
      />
```
No more freezing and I can inject the columns from outside.

**Comment by felansu** [comment] 2021-06-14 21:41
@MariaDimitrova-CoherentSolutions i'm using 1.69.3 and that way works fine too

**Comment by siphu1997** [comment] 2021-07-23 14:55
> I solve this issue inside the component where I`m using MaterialTable component with:
> 
> ```
> const columns = props.columns.map((column) => {
>     return { ...column };
>   });
> ```
> 
> ```
> <MaterialTable
>         data={data}
>         options={options}
>         columns={columns}
>         ...
>       />
> ```
> 
> No more freezing and I can inject the columns from outside.
> I`m using version 1.69.3

BEST SOLUTION. TKS.

**Comment by peacechen** [comment] 2021-07-23 15:22
Reiterating what I posted above in this thread.
> Unfortunately mbrn is inactive and not merging PR's.  Use the official community fork [@material-table/core](https://github.com/material-table-core/core) instead.

The work-arounds posted here don't address the root issue. There are numerous other bugs in this library that have been fixed in the community fork.

**Comment by aliwasif177** [comment] 2021-10-30 16:37
I faced the freezing problem when I tried nested material table in material table. I fixed this by making other component for nested table and set a state to rerender the nested table . Otherwise it'll freeze browser..

**Comment by AdrianoRobson** [comment] 2022-01-25 14:40
> 1.67.0

yes, unfortunately!!!

**Comment by AdrianoRobson** [comment] 2022-01-25 14:41
> Can confirm this is still happening in 1.69.3

yes, unfortunately!!!

**Comment by masbaehr** [comment] 2022-01-25 14:55
this will probably never be fixed as many wrote before. 

note mui v5 also has @mui/x-data-grid which is a perfect replacement
