### ISSUE TITLE
Warning on disabled edit buttons

### ISSUE THREAD

**Issue by avkonst** [mbrn/material-table#1049] opened 2019-08-29 13:30 UTC
**Describe the bug**
If a specific row has got Edit/Delete actions disabled, there is a warning in console:

```
index.js:1375 Warning: Material-UI: you are providing a disabled `button` child to the Tooltip component.
A disabled element does not fire events.
Tooltip needs to listen to the child element's events to display the title.

Place a `div` container on top of the element. 
    in Tooltip (created by WithStyles(Tooltip))
    in WithStyles(Tooltip) (created by MTableAction)
    in MTableAction (created by MTableActions)
    in MTableActions (created by MTableBodyRow)
    in MTableBodyRow (at TableGrid.tsx:258)
```

**Expected behavior**
No warning in the console

**The reproducer:**
```tsx
    <MaterialTable
        columns={[
            {
                field: 'id',
                title: 'ID'
            }
        ]}
        data={[{ id: 'a' }]}
        editable={{
            isEditable: rowData => false,
            onRowUpdate: (newData, oldData) => Promise.resolve()
        }}
    />
```

**Comment by aglt93** [comment] 2019-08-29 21:04
I'm having a similar warning. Probably corresponds to the same issue.

backend.js:1 Warning: Material-UI: you are providing a disabled `button` child to the Tooltip component.
A disabled element does not fire events.
Tooltip needs to listen to the child element's events to display the title.

Place a `div` container on top of the element.

**Comment by mstke** [comment] 2019-09-02 13:20
If you need a quick workaround this problem, you can create an `Action` that appears under condition with the `hidden` prop.

```
const actions={
  [
    rowData => ({
      icon: 'delete',
      isFreeAction: false,
      tooltip: 'Delete User',
      hidden: !rowData.deletable
      onClick:() => {...}
      })
  ]}
```

See the [Conditionals Actions Example](https://material-table.com/#/docs/features/actions) for more info

**Comment by oze4** [comment] 2019-09-03 02:00
@avkonst can you supply the code you are using? An example? Anything...?

**Comment by avkonst** [comment] 2019-09-03 22:37
Hi @oze4 Thank you for considering the ticket. Here is the information I can provide:
> Are you using custom actions or the built in editable prop?
I use both. For editable, the code looks like this:
```tsx
      editable={{
            isEditable: (rowData) => false, // real code uses some logic to make certain rows non editable
            isDeletable: (rowData) => false,
            ....
        }}
```
For custom actions I use either:
```tsx
const actions = []
actions.push((rowData) => ({
      hidden: true,
      icon: '',
      onClick: () => { return; }
}))
....
actions={actions}
```
or this:
```tsx
const actions = []
actions.push((rowData) => ({
                disabled: true,
                iconProps: {
                    fontSize: 'small'
                },
                icon: () => <>1234</>,
                onClick: () => {
                    ....
                }
            }))
....
actions={actions}
```
I also override MTableBodyRow component like the following (the purpose is to remove (not disable) per row edit and delete actions for some rows):
```tsx
const MTableBodyRowOverride = (rowProps: any) => {
        return <MTableBodyRow
                {...rowProps}
                // the following basically removes all actions added by the material-table
                // all my custom actions are marked with the hidden HiddenGroupFold field
                actions={rowProps.actions.filter((i: Function) => !i[HiddenGroupFold])}
            />
        }</>
    }
...
components={{
            Row: MTableBodyRowOverriden
        }}
```

**Comment by oze4** [comment] 2019-09-04 00:44
@avkonst you use all of the above examples in a single instance of Material Table? I am interested in the exact case that brought you here.

> I use both. For editable, the code looks like this:

      editable={{
            isEditable: (rowData) => false, // real code uses some logic to make certain rows non editable
            isDeletable: (rowData) => false,
            ....
        }}

I am specifically interested in the logic that makes certain rows "non editable".  

All in all I think it would be easiest if you supplied a reproducible example that mirrors your issue as close as possible.

**Comment by oze4** [comment] 2019-09-04 01:10
For example, the following code does not produce any errors:

[![Edit material-table](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/material-table-rz6mg?fontsize=14&module=%2Fsrc%2FAppTable.js)

```javascript
export default function AppTable() {
  return (
    <MaterialTable
      actions={[
        rowdata => ({
          icon: () => <DeleteOutlined />,
          disabled: true,
          tooltip: "Delete"
        })
      ]}
      icons={tableIcons}
      data={[
        {
          name: "Rock",
          id: 1
        },
        {
          name: "Paper",
          id: 2
        },
        {
          name: "Scissors",
          id: 3
        }
      ]}
      columns={[
        {
          title: "Item",
          field: "name"
        },
        {
          title: "Item ID",
          field: "id"
        }
      ]}
    />
  );
}
```

**Comment by avkonst** [comment] 2019-09-04 04:41
I will try to find a reproducer. I will try to put some time tomorrow for this. I am sure it is `isEditable: (rowData) => false` causes this. The logic behind this function is less important. In my app it is some rows which do not have permissions to be edited, but you can make every second row non editable, for example.

**Comment by avkonst** [comment] 2019-09-05 01:15
Here is the reproducer:
```tsx
<MaterialTable
        columns={[
            {
                field: 'id',
                title: 'ID'
            }
        ]}
        data={[{ id: 'a' }]}
        editable={{
            isEditable: rowData => false,
            onRowUpdate: (newData, oldData) => Promise.resolve()
        }}
    />
```

**Comment by oze4** [comment] 2019-09-05 13:47
> 
> 
> Here is the reproducer:
> 
> ```tsx
> <MaterialTable
>         columns={[
>             {
>                 field: 'id',
>                 title: 'ID'
>             }
>         ]}
>         data={[{ id: 'a' }]}
>         editable={{
>             isEditable: rowData => false,
>             onRowUpdate: (newData, oldData) => Promise.resolve()
>         }}
>     />
> ```

This does not cause an error... Can you either supply code that actually reproduces the error you are getting, or close this issue out??  It would seem the issue is with your logic, not with Material Table.

Help me help you.

[![Edit material-table](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/material-table-rz6mg?fontsize=14&module=%2Fsrc%2FAppTable.js)

```javascript
export default function AppTable() {
  return (
    <MaterialTable
      icons={tableIcons}
      data={[
        {
          name: "Rock",
          id: 1
        },
        {
          name: "Paper",
          id: 2
        },
        {
          name: "Scissors",
          id: 3
        }
      ]}
      columns={[
        {
          title: "Item",
          field: "name"
        },
        {
          title: "Item ID",
          field: "id"
        }
      ]}
      editable={{
        isEditable: rowData => false,
        onRowUpdate: (newData, oldData) => Promise.resolve()
      }}
    />
```

**Comment by avkonst** [comment] 2019-09-05 23:40
Upgrade dependencies to latest and you will reproduce it:
[Sandbox is here](https://codesandbox.io/s/material-table-ooqc8)

![image](https://user-images.githubusercontent.com/3971413/64391002-1efe4780-d09b-11e9-89b2-f1f2e7e80369.png)

**Comment by oze4** [comment] 2019-09-06 01:59
It looks like this started happening in `v1.49.0` - it doesn't happen prior to that version. [It looks like this commit is the culprit.](https://github.com/mbrn/material-table/commit/3f3413713d4b00e353fcf38b2cc4507ff0ccdb60#diff-1bebc326492d6cec01b923b38a98d992) 

I'm 95% positive that removing the `<span>`'s around the `<IconButton>`'s is what caused this..

<img width="1659" alt="image" src="https://user-images.githubusercontent.com/21092343/64395473-08ff7100-d020-11e9-8955-089425b24f05.png">

**Comment by oze4** [comment] 2019-09-07 18:02
@avkonst I have submitted a pull request that resolves this issue.. Hopefully it will be merged soon.

**Comment by avkonst** [comment] 2019-09-07 19:33
Thanks

**Comment by arkadiusz-wieczorek** [comment] 2019-10-10 09:54
@avkonst that's my workaround, at least I don't receive that error in the console.

```
actions={[
	rowData => ({
		icon: () => (
			<Delete
				color={
					!rowData.disabled
						? 'inherit'
						: 'disabled'
				}
			/>
		),
		tooltip: 'Delete product',
		onClick: (event, rowData) => {
			if (!rowData.disabled) {
				// do stuff
			} else {
				return null;
			}
		},
	})
]}
```

**Comment by rkram3r** [comment] 2019-10-18 18:43
Hi 😃
I had the same problem and created a [PR](https://github.com/mbrn/material-table/pull/1226).

**Comment by oze4** [comment] 2019-10-18 19:07
@rkram3r I've been waiting a loong while to get that simple PR merged lol... :cry:

Sorry =/

**Closed** 2020-05-31 17:33 UTC
