### ISSUE TITLE
Selection and Actions in the same Table Row

### ISSUE THREAD

**Issue by RobertLbebber** [mbrn/material-table#676] opened 2019-06-05 01:29 UTC
Allow tables to have rows with both selection Checkboxes and Action Buttons

**Comment by mbrn** [comment] 2019-06-05 11:19
Hi @RobertLbebber 

This feature requested by others many times. Firstly i advise them to using custom render feature. But i decided to add this feature asap.

**Comment by RobertLbebber** [comment] 2019-06-10 15:23
Yea I think its important because it was weird to track down why the actions were disappearing when the code looks all functionally correct

**Comment by KATT** [comment] 2019-06-17 12:39
I really appreciate your work on Material Table. I've started using it heavily and looking forward to contributing.

Could lend a hand on implementing this, I think.

As I see it there's three types of actions currently:

1. `isFreeAction` top bar action
2. Top bar action _when rows are selected_
3. Actions on rows

The type of #2 and #3 are currently implicitly defined based on if it's a selectable table. Correct me if I'm wrong or missed something

I would propose one or these two approaches (backwards-compatible with just deprecating  the old API):

1. Move row actions to `columns[]`. Would make it very explicit what is where.
2. Explicit `position`-prop in the `actions[]` array with 4 options + deprecate `isFreeAction`
   1. `auto` (default) - existing behaviour (it can figure out the one of the below)
   2. `header`
   3. `headerOnSelect` - Show when a row is selected
   4. `row`

**Comment by yuri3** [comment] 2019-10-03 13:58
Hi mbrn, can you tell me please the above feature requested by RobertLbebber, will be added?
if so when?

**Comment by ahameleon** [comment] 2019-10-08 10:29
Also waiting for this feature. Any updates as of yet?

**Comment by jayarjo** [comment] 2019-10-08 16:43
Related: https://github.com/mbrn/material-table/issues/1107. I've also posted solution to this problem on [SO](https://stackoverflow.com/questions/58150039/material-table-how-to-do-selectable-and-editable-table/58153038#58153038) 

@KATT unfortunately only @mbrn has enough insight on the project to evaluate your suggestion. Hope he will the time to post some thoughts. 

Until then you folks could try the solution from the thread I've referenced above.

**Comment by jayarjo** [comment] 2019-10-08 16:47
Also related: https://github.com/mbrn/material-table/issues/648

**Comment by tafelito** [comment] 2019-10-14 23:33
@jayarjo in addition of having actions in the row level, it would be great to also have an option in the toolbar to hide the actions there if they are shown at the row level. 
what I'm doing now is using your example for the TableBodyRow and  the Toolbar but I added an option to not show the actions if it's a row action here

https://github.com/mbrn/material-table/blob/2dd0ca780abeda0b98445e986b9a39630aaca10e/src/components/m-table-toolbar.js#L168

**Comment by Cristy94** [comment] 2020-03-09 00:21
Was this fixed? How to have both Selection and Action buttons on each row?

**Comment by luciobordonaro** [comment] 2020-05-05 09:34
Hi everyone!
I managed to have both selection and actions in the same table row without customising the `Row` component.

To do it, when managing actions don't use the `isFreeAction` flag but instead use the `position` value.
It is not documented on the official website, but it is documented in the TS declarations that you can find here `node_modules/material-table/types/index.d.ts`.

```
export interface Action<RowData extends object> {
  disabled?: boolean;
  icon: string | (() => React.ReactElement<any>);
  isFreeAction?: boolean;
  position?: 'auto' | 'toolbar' | 'toolbarOnSelect' | 'row';
  tooltip?: string;
  onClick: (event: any, data: RowData | RowData[]) => void;
  iconProps?: IconProps;
  hidden?: boolean;
}
```

So if you want an action to be of scope row, simply pass `position: row` while for buttons to be shown on toolbar when selecting use `position: toolbarOnSelect`.

In my specific use case I mapped them to an enum like this:
```
export enum ActionPosition {
  default = "toolbar",
  row = "row",
  selection = "toolbarOnSelect",
}
```

Hope this helps you!

**Comment by mmihic96** [comment] 2020-05-15 14:16
@luciobordonaro This is not working for me. 

I using "actions" prop. Exampl:
![image](https://user-images.githubusercontent.com/28544145/82060278-7394a080-96c7-11ea-81ae-57ee1fb57ab8.png)

I hope it will be fixed soon.

**Comment by oze4** [comment] 2020-05-15 15:56
@luciobordonaro would you mind making a basic example using CodeSandbox for this? I cannot get it to work even with your instructions.

**Comment by oze4** [comment] 2020-05-15 16:03
Ok so I managed to get it working.  You CANNOT use a function for your actions if you want to use the position property..

You can view [a live demo here](https://stackblitz.com/edit/react-csb18b?embed=1&file=index.js)

```javascript
// This **DOES NOT** work
const actions = [
  rowData => {
    return {
      icon: () => <RemoveCircleIcon />,
      tooltip: <h1>I am a tooltip</h1>,
      onClick: (event, rowData) => alert(JSON.stringify(rowData, null, 2)),
      position: "row"
    }
  }
];
```

```javascript
// This **DOES** work
const actions = [
  {
    icon: () => <RemoveCircleIcon />,
    tooltip: <h1>I am a tooltip</h1>,
    onClick: (event, rowData) => alert(JSON.stringify(rowData, null, 2)),
    position: "row"
  }
];
```

```javascript
// Full demo
import React, { useState } from "react";
import { render } from "react-dom";
import MaterialTable from "material-table";
import tableIcons from "./TableIcons.js";
import { RemoveCircleOutlineOutlined as RemoveCircleIcon } from '@material-ui/icons';

const rando = max => Math.floor(Math.random() * max);
const words = ["Paper", "Rock", "Scissors"];
const data = [];

for (let i = 0; i < 100; i++) {
  data.push({
    id: rando(300),
    name: words[i % words.length]
  });
}

const columns = [
  { title: "Id", field: "id" },
  { title: "Name", field: "name" }
];

const actions = [
  {
    icon: () => <RemoveCircleIcon />,
    tooltip: <h1>I am a tooltip</h1>,
    onClick: (event, rowData) => alert(JSON.stringify(rowData, null, 2)),
    position: "row"
  }
];

const App = () => {
  return (
    <MaterialTable
      actions={actions}
      data={data}
      icons={tableIcons}
      columns={columns}
      options={{
        selection: true,
      }}
    />
  );
};

render(<App />, document.querySelector("#root"));
```

**Comment by mmihic96** [comment] 2020-05-15 16:50
@oze4 
Good example. This working. But there is an issue, how I can control disabled/inactive in that case?
As You see in my example, disable action depending on row status. 
Before You answered question I already put "Actions" under column prop. 


Thank You again for fast answer.

**Comment by luciobordonaro** [comment] 2020-05-15 17:11
> Ok so I managed to get it working. Two things:
> 
> * You CANNOT use a function for your actions if you want to use the position property
> * The `icon` prop has to be either a function or just the variable name of the icon you are using (ie: `icon: () => <SomeIcon />,` or `icon: SomeIcon,`, but **NOT** `icon: <SomeIcon />`)

Yep, sorry forgot to mention that I wasn't working at the laptop to provide my example.
I'm using array for actions and names for icons as you mentioned.

This library is very powerful but lacks of documentation, maybe we can help improving this specific use case 👍

**Comment by oze4** [comment] 2020-05-15 17:39
@luciobordonaro I have been keeping up with this repo for the past year or so and they are EXTREMELY slow moving, they don't address open issues, and they don't address PR's..  I even volunteered to help out (which would mean providing me with merge permissions, etc..), but I never got a response on that (shocker)..

I have been giving some serious thought to forking this repo and resolving issues/maintaining that fork.. something like `material-table-2` or whatever.. 

@mmihic96 while I know this is a hack, and not anywhere close to ideal, you can accomplish what you want by overriding the Row component, and enabling/disabling the action from there..

[I have updated the live demo](https://stackblitz.com/edit/react-csb18b?embed=1&file=index.js)

```javascript
import React, { useState } from "react";
import { render } from "react-dom";
import MaterialTable, { MTableBodyRow } from "material-table";
import tableIcons from "./TableIcons.js";
import { 
  RemoveCircleOutlineOutlined as RemoveCircleIcon,
  AccountCircleOutlined as AccountCircleIcon
} from '@material-ui/icons';

const rando = max => Math.floor(Math.random() * max);
const words = ["Paper", "Rock", "Scissors"];
const data = [];

for (let i = 0; i < 100; i++) {
  data.push({
    id: rando(300),
    name: words[i % words.length]
  });
}

const columns = [
  { title: "Id", field: "id" },
  { title: "Name", field: "name" }
];

const actions = [
  {
    name: 'remove', // Added custom name property so we know which action to check for
    icon: () => <RemoveCircleIcon />,
    tooltip: <h1>I am a tooltip</h1>,
    onClick: (event, rowData) => alert(JSON.stringify(rowData, null, 2)),
    disabled: false, // Set disabled to false by default for all actions
    position: "row"
  },
  {
    name: 'account',
    icon: () => <AccountCircleIcon />,
    tooltip: <h1>I am a tooltip</h1>,
    onClick: (event, rowData) => alert(JSON.stringify(rowData, null, 2)),
    disabled: false,
    position: "row"
  }
];

const App = () => {
  return (
    <MaterialTable
      actions={actions}
      data={data}
      icons={tableIcons}
      columns={columns}
      components={{
        Row: props => {
          const propsCopy = { ...props };
          propsCopy.actions.find(a => a.name === 'remove').disabled = propsCopy.data.id < 100;
          propsCopy.actions.find(a => a.name === 'account').disabled = propsCopy.data.name !== 'Paper';
          return <MTableBodyRow {...propsCopy} />
        }
      }}
      options={{
        selection: true,
      }}
    />
  );
};

render(<App />, document.querySelector("#root"));
```

**Comment by mmihic96** [comment] 2020-05-15 17:43
@oze4 Thanks. Everything working.

**Comment by ifndefdeadmau5** [comment] 2020-05-27 02:11
There's a way that can use action as a function, what causes the problem is this line
https://github.com/mbrn/material-table/blob/dee28035ad478cede5fa2da9f41df8409a62dead/src/material-table.js#L124-L132
which check if `options.selection` is true and the type of action is function. and then force to set 'toolbarOnSelect'.

Hence, we just can provide `options.selection` to the `m-table-body-row` directly instead of specifying it in `options` so that we can kinda bypass above code block.
```js
 Row: props => {
          return (
            <MTableBodyRow
              {...{
                ...props,
                options: {
                  ...props.options,
                  selection: true,
                },
              }}
            />
          );
        },
```
if you also need 'check-all' checkbox on header, you also have to override Header
```js
 Header: ({ columns, ...props }: any) => {
          return (
            <TableHead>
              <TableRow>
                {!!parentChildData && <TableCell />}
                {selection && (
                  <TableCell padding="none">
                    {props.showSelectAllCheckbox && (
                      <Checkbox
                        indeterminate={
                          props.selectedCount > 0 &&
                          props.selectedCount < props.dataCount
                        }
                        checked={
                          props.dataCount > 0 &&
                          props.selectedCount === props.dataCount
                        }
                        onChange={(event, checked) =>
                          props.onAllSelected && props.onAllSelected(checked)
                        }
                      />
                    )}
                  </TableCell>
                )}
                // and rest of columns goes here
          );
        },
```

Note that there are still other component that consumes `options.selection` prop besides `m-table-body-row`, you'll also need to pass them in case you need those features.

**Closed** 2020-05-31 17:35 UTC
Labels: enhancement

**Comment by kunalgoyal1992** [comment] 2020-06-07 08:56
How do I pass rowData to actions in this case?
I found this: 
[https://github.com/mbrn/material-table/issues/1007]

But this method hides the icon right away. Actions won't show icon if we use his method.
[left-panel.txt](https://github.com/mbrn/material-table/files/4741602/left-panel.txt)

Here I have passed StoreId in props of Icon (Add Sub Store) but it completely hides the icon. Could you show me a workaround or something that could help me get this done?

**Comment by daviddjp** [comment] 2020-07-15 22:34
> @luciobordonaro I have been keeping up with this repo for the past year or so and they are EXTREMELY slow moving, they don't address open issues, and they don't address PR's.. [I even volunteered to help out](https://github.com/mbrn/material-table/issues/1171#issuecomment-540355132) (which would mean providing me with merge permissions, etc..), but I never got a response on that (shocker)..
> 
> I have been giving some serious thought to forking this repo and resolving issues/maintaining that fork.. something like `material-table-2` or whatever..
> 
> @mmihic96 while I know this is a hack, and not anywhere close to ideal, you can accomplish what you want by overriding the Row component, and enabling/disabling the action from there..
> 
> [I have updated the live demo](https://stackblitz.com/edit/react-csb18b?embed=1&file=index.js)
> 
> ```js
> import React, { useState } from "react";
> import { render } from "react-dom";
> import MaterialTable, { MTableBodyRow } from "material-table";
> import tableIcons from "./TableIcons.js";
> import { 
>   RemoveCircleOutlineOutlined as RemoveCircleIcon,
>   AccountCircleOutlined as AccountCircleIcon
> } from '@material-ui/icons';
> 
> const rando = max => Math.floor(Math.random() * max);
> const words = ["Paper", "Rock", "Scissors"];
> const data = [];
> 
> for (let i = 0; i < 100; i++) {
>   data.push({
>     id: rando(300),
>     name: words[i % words.length]
>   });
> }
> 
> const columns = [
>   { title: "Id", field: "id" },
>   { title: "Name", field: "name" }
> ];
> 
> const actions = [
>   {
>     name: 'remove', // Added custom name property so we know which action to check for
>     icon: () => <RemoveCircleIcon />,
>     tooltip: <h1>I am a tooltip</h1>,
>     onClick: (event, rowData) => alert(JSON.stringify(rowData, null, 2)),
>     disabled: false, // Set disabled to false by default for all actions
>     position: "row"
>   },
>   {
>     name: 'account',
>     icon: () => <AccountCircleIcon />,
>     tooltip: <h1>I am a tooltip</h1>,
>     onClick: (event, rowData) => alert(JSON.stringify(rowData, null, 2)),
>     disabled: false,
>     position: "row"
>   }
> ];
> 
> const App = () => {
>   return (
>     <MaterialTable
>       actions={actions}
>       data={data}
>       icons={tableIcons}
>       columns={columns}
>       components={{
>         Row: props => {
>           const propsCopy = { ...props };
>           propsCopy.actions.find(a => a.name === 'remove').disabled = propsCopy.data.id < 100;
>           propsCopy.actions.find(a => a.name === 'account').disabled = propsCopy.data.name !== 'Paper';
>           return <MTableBodyRow {...propsCopy} />
>         }
>       }}
>       options={{
>         selection: true,
>       }}
>     />
>   );
> };
> 
> render(<App />, document.querySelector("#root"));
> ```

Thanks, man. That worked perfectly.

**Comment by linkjane** [comment] 2020-07-22 10:04
@oze4 Thank you so much for your example， and then I tried to modify it like this based on your code， and it works to me，I only want to use the feature of action disabled and selection at the same time. but it also can give a formatAction that has params data and action by props.


```  javascript
Row: (props) => {
        const propsCopy = { ...props };
        // or add a format action function
        // formatAction(originAction, propsCopy.data) => finalAction;
        propsCopy.actions = propsCopy.actions.map((action) => {
          return {
            ...action,
            disabled: action.disabled || action.disabledFunc?.(propsCopy.data)
          };
        });
        return <TableRow {...propsCopy} />;
      }


```
and how to write action is
``` javascript
  action=[{
    icon: () => <Edit />
    position: 'row',
    disabledFunc: (row) => row.status === 2,
}]
```
I use typescript

**Comment by grking8** [comment] 2020-08-14 16:47
Sorry if this is obvious, but why do we copy the props in the below?

```js
      components={{
        Row: props => {
          const propsCopy = { ...props };
          propsCopy.actions.find(a => a.name === 'remove').disabled = propsCopy.data.id < 100;
          propsCopy.actions.find(a => a.name === 'account').disabled = propsCopy.data.name !== 'Paper';
          return <MTableBodyRow {...propsCopy} />
        }
      }}
```

**Comment by giladbr** [comment] 2021-04-18 10:23
Thank you for this thread and especially to @luciob for `position: "row"` that solved the problem like a silver bullet, concluded an hour or two of searching and experimenting and saved me many more :-)

**Comment by cursedmagician** [comment] 2021-08-12 13:40
I ran into the issue of needing both an action that is a function as well as a selection based column. Having read this thread, I started writing a new version of the m-table-action component and came across a solution in the existing code.

Below would work normally, but not if a selection is defined
```javascript  
const actions = [
      { // function derived action which is disabled based on rowData
            rowData => ({
                name: 'Complete',
                icon: () => 'done',
                tooltip: 'Complete the activity,
                onClick: (event, rowData) => alert(JSON.stringify(rowData, null, 2)),
                disabled: rowData.someOtherField==='',
                position: "row"
            })
      }
]
```

if you change it so that the function is moved to action then it will work for selection based tables

Below would work normally, but not if a selection is defined
```javascript  
const actions = [
      { // function derived action which is disabled based on rowData
            position: "row", //This must be on the same level as the action function to prevent it being filtered.
            action: rowData => ({
                name: 'Complete',
                icon: () => 'done',
                tooltip: 'Complete the activity,
                onClick: (event, rowData) => alert(JSON.stringify(rowData, null, 2)),
                disabled: rowData.someOtherField==='',
            })
      }
]
```

**Comment by azyouness** [comment] 2021-09-30 15:35
The simplest way I come up with to make actions work with selection without problems is:

- All Actions must be objects (even function actions, as explained in the code below)
- The position: 'row', must added to all actions

```
const actions = [
  { // To make "object actions" work just add: position: "row",
    icon: DelIcon,
    position: "row",
    tooltip: "Delete",
    onClick: (e, row) => onDelete(row),
  },
  { // To make "function actions" work don't use function directly instead wrap it inside an object with a property named "action" along side "position" property
    position: "row",
    action: (rowData) => ({
      icon: rowData.status === "active" ? BlockIcon : UnblockIcon,
      onClick: (e, row) => onUpdateStatus(row),
    }),
  },
];
```
