### ISSUE TITLE
Bug in v1.62.0 and higher - table cell font style is set on inherit

### ISSUE THREAD

**Issue by shaselboeck** [mbrn/material-table#2124] opened 2020-07-03 07:35 UTC
Table font style is broken. In v1.61.0 everything is good, but from v1.62.0 and higher the font style is broken, see attached ...

v1.62.0
![material-table@1 62 0](https://user-images.githubusercontent.com/1867700/86444020-6b90ce80-bd10-11ea-9c55-adb8b5c64606.jpg)

v1.61.0
![material-table@1 61 0](https://user-images.githubusercontent.com/1867700/86444022-6cc1fb80-bd10-11ea-88cb-053a39261a7b.jpg)

**Comment by mfmsajidh** [comment] 2020-07-11 10:39
Duplicate of #2080

**Closed** 2020-10-16 11:22 UTC
Labels: bug, wontfix
