### ISSUE TITLE
Browser Freezes in Version 1.69.0 on material table render

### ISSUE THREAD

**Issue by kumarunster** [mbrn/material-table#2486] opened 2020-09-23 10:55 UTC
We noticed strange freezes in our application, which we were able to trace back to Material Table.

The freeze is caused by the new introduced function `reducePercentsInCalc' from [PR #2351](https://github.com/mbrn/material-table/pull/2351/files)

the calc parameter is growing exponentially, so that the indexOf call takes huge amount of time on that large string.

Here couple of screenshots form the cpu profiler.

<img width="731" alt="Bildschirmfoto 2020-09-23 um 10 26 27" src="https://user-images.githubusercontent.com/2104820/94002724-8cf6d900-fd9a-11ea-8df4-1ad7783c266c.png">
<img width="805" alt="Bildschirmfoto 2020-09-23 um 10 26 53" src="https://user-images.githubusercontent.com/2104820/94002746-94b67d80-fd9a-11ea-80d7-acc2f0b54230.png">

further analysis makes me sure, that the really cause for that input parameter growing is following code in [data-manager.js](https://github.com/mbrn/material-table/blob/e81700a2d2d0938ca60eec60b6c2e73dc87f72ea/src/utils/data-manager.js#L63-L94)

in my opinion the `undefinedWidthColumns` is missing check for tableData.width, which is assigned few lines later, once the column gets rendered.

this is the possible cause for already reported bugs #2451 and #2453 

@Domino987, @mbrn what is your thought about that?

**Comment by Domino987** [comment] 2020-09-23 10:58
Hi thank you for the detailed evaluation . This problem is known and there is at least one PR to address this, but since we cannot get hold of mbrn since weeks, I do not know when this can be merged. Reverting back to 1.68 removes the Problem, until this is solved.

**Comment by kumarunster** [comment] 2020-09-23 11:05
@Domino987 thanks for quick reply. Could you point me to that PR? In my opinion the fix should be in data-manager#getColumns, not in common-values#reducePercentsInCalc.

**Comment by RobertGardner** [comment] 2020-09-23 19:19
I believe the problem is in (perhaps "also in") data-manager#setColumns.

At the top of that method it finds all the columns that do not have defined widths, using:
```
columns.filter(function (c) {
   return c.width === undefined && !c.hidden;
});
```

It then proceeds to calculate a width and assign it to `columnDef.tableData.width`.

When `setColumns` gets called again (which happens frequently), it doesn't recognize that the column width has now been set for those columns because it is only checking `c.width`. So it recalculates but builds the new width based on the old `columnDef.tableData.width`. So `columnDef.tableData.width` keeps growing indefinitely.

It seems like the correct fix is to change the check at the top of `setColumns` to be:
```
columns.filter(function (c) {
   return c.width === undefined && c.columnDef.tableData?.width === undefined && !c.hidden;
});
```

**Comment by gxtaillon** [comment] 2020-09-27 21:43
Likely related are #2451, #2418, #2404

**Comment by kumarunster** [comment] 2020-09-28 05:30
Thanks @gxtaillon for linking the issues.

Any news from @mbrn? I hope he is well.

**Comment by kumarunster** [comment] 2020-10-07 08:48
@mbrn any plans on this? Do you want a PR?

**Comment by Domino987** [comment] 2020-10-07 08:59
It's already done. A quick fix with 1.69.1 was released of #2423 and a deep fix which is not merged yet of #2510 . Thank you though for the help.

**Comment by kumarunster** [comment] 2020-10-07 09:24
@Domino987 thanks for linking PR's here. As mentioned above, it does not fix the main issue. Main issue is in the data-manager.js. @RobertGardner provided a proposal for that, which should fix everything on the source. Please take it into account. Then the `reducePercentsInCalc`will run fast and safe.

**Closed** 2020-11-17 09:04 UTC
Labels: bug

**Comment by kvskranthikumar** [comment] 2020-11-17 11:30
I can still see the issue with the latest version 1.69.2
Here is the sample to recreate this issue -

https://codesandbox.io/s/compassionate-meitner-802l6

Just clicking on the rows hangs the browser.

**Comment by kvskranthikumar** [comment] 2020-11-19 12:27
@mbrn, any updates on this issue?
Due to this, we can't upgrade the material-table version to the latest version.

Here is the sample to recreate this issue -
https://codesandbox.io/s/compassionate-meitner-802l6

Just clicking around 10 to 15 times on the rows hangs the browser.

**Comment by yhaelopez** [comment] 2020-12-03 21:48
Any updates on this? I'm having the same issue.

**Comment by peacechen** [comment] 2020-12-11 23:09
@RobertGardner 
Thanks for the insight into the width calculations growing infinitely. The root problem is a logic error in the order of operations. See PR #2689

**Comment by peacechen** [comment] 2021-01-08 14:23
Unfortunately mbrn is inactive and not merging PR's. Use the official community fork [@material-table/core ](https://github.com/material-table-core/core)instead.
