### ISSUE TITLE
RemoteData query's "orderDirection" always reset to "asc"

### ISSUE THREAD

**Issue by aldabil21** [mbrn/material-table#2177] opened 2020-07-15 11:03 UTC
Hi fellows,

Thx for the nice package.

After my last update to 1.65.0 (previous was 1.57.2), I noticed some issue with sorting columns in remote data.

**The issue**
The data query's ***orderDirection*** is always *"asc"*. never changed to *"desc"*.
After some digging, the ***orderby*** in ***dataManager*** is always been reset to the default -1, triggered by the ***shouldReload*** and call ***dataManager.changeOrder*** with the default values.

**Tested code**
````
import React, { useState, forwardRef } from "react";
import MaterialTable from "material-table";
import ArrowDownward from "@material-ui/icons/ArrowDownward";

function App() {
  const [query, setQuery] = useState();
  const [pageSize, setPageSize] = useState(5);
  return (
    <>
      {/* REMOTE Example... Orderby always reset to defaul -1 when using (isInit ||...) */}
      <pre style={{ textAlign: "center", whiteSpace: "pre-wrap" }}>
        {JSON.stringify(query)}
      </pre>
      <MaterialTable
        title="Remote Data Preview"
        icons={{
          SortArrow: forwardRef((props, ref) => (
            <ArrowDownward {...props} ref={ref} />
          )),
        }}
        columns={[
          {
            title: "Avatar",
            field: "avatar",
            render: (rowData) => (
              <img
                style={{ height: 36, borderRadius: "50%" }}
                src={rowData.avatar}
                alt="avatar"
              />
            ),
          },
          { title: "Id", field: "id" },
          { title: "First Name", field: "first_name" },
          { title: "Last Name", field: "last_name" },
        ]}
        data={(query) => {
          setQuery(query);
          return new Promise((resolve, reject) => {
            let url = "https://reqres.in/api/users?";
            url += "per_page=" + query.pageSize;
            url += "&page=" + (query.page + 1);
            fetch(url)
              .then((response) => response.json())
              .then((result) => {
                resolve({
                  data: result.data,
                  page: result.page - 1,
                  totalCount: result.total,
                });
              });
          });
        }}
        options={{
          pageSize: pageSize,
        }}
        onChangeRowsPerPage={(size) => setPageSize(size)}
        onOrderChange={(colId, ord) =>
          console.log("OnOrderChange: [ColId: " + colId + ", Dir: " + ord + "]")
        }
      />

      {/* Local example... no issues with using both (isInit ||... or isInit && ...) */}
      {/* <MaterialTable
        title="Basic Sorting Preview"
        columns={[
          { title: "Name", field: "name" },
          { title: "Surname", field: "surname" },
          { title: "Birth Year", field: "birthYear", type: "numeric" },
          {
            title: "Birth Place",
            field: "birthCity",
            lookup: { 34: "İstanbul", 63: "Şanlıurfa" },
          },
        ]}
        data={[
          { name: "Mehmet", surname: "Baran", birthYear: 1987, birthCity: 63 },
          {
            name: "Zerya Betül",
            surname: "Baran",
            birthYear: 2017,
            birthCity: 34,
          },
        ]}
      /> */}
    </>
  );
}

export default App;
````

**Screenshot of Log in dataManager & App**
![Image](https://i.ibb.co/h8GhC3c/log.png)

**Workaround**
I've changed

`
var shouldReorder = isInit || ...
`
to
`
var shouldReorder = isInit &&... 
`

which fixed the issue. Perhaps you may implement your own solution to the issue. 

Best of wishes...

**Comment by ilmiont** [comment] 2020-07-28 09:14
I'm hitting this too; from my testing, it's present in all versions from v1.61.0 onwards (v1.60.0 the last good version).

Using remote data feature at all results in inoperable sorting as the headers don't correctly show the current sort column / direction.

**Comment by TheGameNewWorldOrder** [comment] 2020-08-06 03:03
It doesn't even work in your demo here: https://material-table.com/#/docs/features/remote-data

**Comment by mukesh-pathak-by** [comment] 2020-08-14 13:04
Even i am facing this issue latest release. Can someone let me know where we can where change needs to made; I was not able to figure that out

Thanks in advance

**Comment by aldabil21** [comment] 2020-08-15 19:15
@mukesh-pathak-by 

This line:
https://github.com/mbrn/material-table/blob/04309da053cf7bd4cf91b024c555dd9e2f5d6f67/src/material-table.js#L102

Changing this line from `isInit || ` to `isInit &&` have fixed the issue for me.

**Comment by mukesh-pathak-by** [comment] 2020-08-15 19:30
@aldabil21 

If this fix is correct. Can we raise PR to fix this issue.

This will help others who are facing this issue.

@Domino987 @mbrn Please suggest on the same.

Regards,
Mukesh Pathak

**Comment by aldabil21** [comment] 2020-08-16 11:37
Well, checks has failed. Sorry...

**Comment by Domino987** [comment] 2020-08-16 16:23
That's just the prettier CI, maybe try to run prettier manually in your codebase before you push something. But that is not a reason for it not to be merged.

**Comment by thiagotigaz** [comment] 2020-08-18 05:00
I have the same issue with remote data fetch.

**Comment by Domino987** [comment] 2020-08-26 18:47
I think this is not an error actually. The data needs to be reversed by the backend, because it only renders one page at a time, there is no way for MT to reverse all the data. That is why the query passed to data contains SO #2324

**Closed by Domino987** 2020-08-26 18:47 UTC
Labels: bug

**Comment by TheGameNewWorldOrder** [comment] 2020-09-03 06:47
@Domino987 the bug with material table here is that the 'orderDirection' inside query always returns 'asc'. Clicking the sorting arrow doesn't toggle the direction. We need to use this string value to map to our endpoint param for sorting. Could you provide a simple example of how to toggle the direction in UI then we can deal with our backend?

**Comment by gxtaillon** [comment] 2020-09-28 01:10
@TheGameNewWorldOrder I haven't tested on 1.69.x, but on 1.68.x I found a workaround, see https://github.com/mbrn/material-table/issues/2322#issuecomment-699708067

**Comment by ilmiont** [comment] 2020-09-28 08:04
> I think this is not an error actually. The data needs to be reversed by the backend, because it only renders one page at a time, there is no way for MT to reverse all the data because it only knows of the current page. And the reversed data shows a totally different page for the reverse order. That is why the query passed to data contains orderDirection to make the backend sort it correctly. So #2324 and #2330 do not fix it. And the backend has to reverse the order of the data and the the MT table does not track it anymore.
> I added this PR #2375 to fix this issue to sync the current state and the query state, but this again is nor error but should be relieved with that.

This really shouldn't have been closed.

The bug is as described by @TheGameNewWorldOrder  above - the table sets 'orderDirection' in the query incorrectly, so it's always the same value. Henceforth there's no way of informing the server what sorting to apply.

This worked flawlessly in v1.61 and older; I'm currently locking `material-table` to v1.61 in my projects to avoid this.

I will try the workaround above from @gxtaillon next.

**Comment by TheGameNewWorldOrder** [comment] 2020-11-25 23:58
@ilmiont Have you tried the workaround mentioned above? Any luck?

**Comment by ilmiont** [comment] 2020-11-26 09:00
@TheGameNewWorldOrder  I actually haven't tried it yet, I'm still using `material-table@1.61` instead which currently works well for me as I don't need any of the features from subsequent releases (yet).

The workaround looks like it should work but is also a clear hack, plus it would take a while for me to integrate to all the projects I use `material-table` with.

I still don't understand why this issue was closed by @Domino987 ... it's a clear issue, a regression since previous releases and contradicts the documntation.
