### ISSUE TITLE
Material-Table Mutates Item Passed Through data Prop

### ISSUE THREAD

**Issue by kbi-daniel** [mbrn/material-table#1371] opened 2019-11-21 17:30 UTC
**Describe the bug**
We are passing an array of objects from our app's Redux state to the data prop. Material Table mutates that Redux state by adding a `tableData` property to each object in the array. This unexpected mutation of our apps Redux state caused some of our data to be corrupted when we saved the state back to our database (now with the inclusion of the `tableData` property.

**To Reproduce**
1. Pass an array of objects into the data prop.
2. console.log the array of objects on component render
3. note that each object in array now has the added `tableData` property.

**Expected behavior**
Material Table should not mutate items passed to data prop.

**Comment by kbi-daniel** [comment] 2019-11-21 17:34
I created fork that solves the mutation problem.  However, I am not sure if this approach has any other unforeseen consequences.
https://github.com/kbi-daniel/material-table/tree/bug/prevent-data-prop-mutate

**Comment by Domino987** [comment] 2019-11-21 18:08
This already known was tried to be solved #1174 here.
But this removes the reference to the existing data item on callbacks.
If the object is searched via shallow compares like this:
`onRowClick={(event, row)=> data.find(d => d === r}`
it will fail because the reference changed.

The way material-table saves its data has to be changed to turn the dependencies around like
` row = {id: index, rowData: row }};`
And what is written in tableData is just saved in the row object while the original data stays the the rowData object (same reference and no mutation).
But since accessing the data would have to be changed at all places, this will be a lot of work since tableData has 200 references in the project which all have to be changed to fit the new scheme.
![image](https://user-images.githubusercontent.com/17567991/69364198-30b2bc80-0c92-11ea-9fc1-58037ba1c4de.png)
I am a strong advocate to remove this prop mutation but as I said, it will be a lot of work.

Maybe be can create a branch and work on it together?
@mbrn , what do you think?

**Comment by amickael** [comment] 2019-11-21 20:00
I've had the same issue, it becomes especially bad when dealing with Redux. Hopefully it will be addressed in the future (I'd be happy to help), but right now I've worked around it by passing data as such:

```js
<MaterialTable data={tableData.map(item => Object.assign({}, item))} ... />
```

That way the data passed to the component is a copy instead of the original, where `tableData` is being supplied by state/prop/selector so it can update with changes.

**Comment by kbi-daniel** [comment] 2019-11-22 16:24
@amickael we came up with a similar solution as well.

That being said, does it make sense to anyone else (and do you think it would work), to add a small utility function to the package to basically duplicate the code suggested by @amickael.

For example...

```
import MaterialTable, {noMutate} from 'material-table'

<MaterialTable data={noMutate(reduxData)} ... />
```

**Comment by Domino987** [comment] 2019-11-22 16:57
While this might work for most use cases, it does not fix the underlying problem and the reference would still be different if that is needed.
Additionally, it would remove the selection, filter etc on every render of the parent.

**Comment by amickael** [comment] 2019-11-22 17:35
@Domino987 Agreed, this is not a permanent solution. It also will not work if you have deeply nested structures. I wouldn’t recommend this approach be implemented inside of the component.

**Comment by Domino987** [comment] 2019-11-23 13:10
@amickael , @kbi-daniel  Do you guys agree that `row = {id: index, rowData: row, ...otherTableRelatedData }};` is the best way to do that and return rowData for the callbacks and access the field with row.rowData.field?

Or how would you represent the data?

**Comment by amickael** [comment] 2019-11-25 15:08
@Domino987 I think that's fine if rowData is not mutated afterward.

**Comment by Domino987** [comment] 2019-11-25 18:04
Ok I guess we could open a new branch and start to change all the 200 relevant sections.

**Comment by narciero** [comment] 2020-02-24 19:02
It’s worth mentioning that anyone using `@apollo/client` v3 will be unable to use this library as the query results (which I display in a table) are deeply frozen and therefore an exception is thrown when you try to set `tableData`

**Comment by Domino987** [comment] 2020-02-24 19:43
Since this becomes more and more a problem, I will branch it tomorrow and will start on the changes. I'll link or here and hope some of you will make some PRs to it to get it done as soon as possible.

**Comment by Domino987** [comment] 2020-02-24 21:35
On the other hand, if @mbrn agrees that we should not mutate the data and devs should not rely on shallow object reference, we could keep #1174 and just mark is as breaking change it it would be solved. That would be the easiest and cleanest in my opinion. What do you say @mbrn ?

**Comment by cutamar** [comment] 2020-04-17 02:55
@Domino987 any updates on this? I am trying to use relay with hooks, but it won't work if material-table keeps mutating the data object.

**Comment by Domino987** [comment] 2020-04-25 12:54
@cutamar Sorry for the delay. I open a branch, but as discussed, it needs a lot of work.
https://github.com/Domino987/material-table/tree/mutation-removal

**Comment by manuFL** [comment] 2020-05-15 13:05
still no news from the master branch?

**Comment by kaviyarasu1987** [comment] 2020-06-21 08:52
is it closed?

**Comment by Domino987** [comment] 2020-06-25 12:08
We are currently closing the issues and PRs. After that we will rewrite to use Context and function components. During this, we will also remove the mutations. So I will close this issue, because its a known issue and we will fix this asap.

**Closed by Domino987** 2020-06-25 12:08 UTC

**Comment by geohuz** [comment] 2020-11-26 02:26
Any news for the mutation-removal?

**Comment by Andkoo** [comment] 2021-03-12 14:15
@geohuz as of 12.03.2021 the issue is still not fixed and by doing object copying workarounds like

```<MaterialTable data={myData.map(item => ({ ...item }))} />```

you can completely destroy the performance of your app. Clicking on table rows will gradually slow your app down up to the point of a complete freeze after about 5th click. Especially if you memoize table columns, becase for some reason unknown to me, MT has problems with that. Column memoization makes the performance like 30% worse. If you want to see how to make sure that everything will be properly memoized, 100% performant and no data mutation will occur, you can check out [this minimal example I've created](https://codesandbox.io/s/material-table-avoid-performance-and-data-mutation-issues-g40wh?file=/src/App.tsx).

**Comment by daniel-sim** [comment] 2021-03-12 14:35
Switched back to Material UI's improved table component for this reason. Their commercial table looks promising too.

**Comment by ramoizain** [comment] 2021-10-04 01:01
This is still a pretty nasty problem with Material-Table... @Domino987 what's the deal?

**Comment by Domino987** [comment] 2021-10-04 03:47
As already discussed in a bunch of issues, i wanted to remove it but mbrn blocked it. After he went afk, we cannot change anything about it because no new code can be merged. We have a community fork, in which this is removed, material-table-core. You can check it out.

**Comment by ramoizain** [comment] 2021-10-04 04:40
@Domino987, thank you! I didn't realize there was a new fork. Works very well!
