### ISSUE TITLE
Changing position of the pagination element

### ISSUE THREAD

**Issue by p34m5** [mbrn/material-table#540] opened 2019-05-03 10:53 UTC
Hi,

Thank you for the great library. I have a question about the position of the pagination component. Is there a way to move it from the bottom to the top of the table?

I went through the documentation but couldn't find any way to do that.

Thank you for your help!

**Comment by mbrn** [comment] 2019-05-03 11:02
Hi @p34m5 ,

Thanks. Currently you can not. But i can add a option to paginationPosition (top|bottom|both) asap.

**Comment by P3y4m** [comment] 2019-05-03 11:35
Great, looking forward to having it.

**Comment by adamsoffer** [comment] 2019-07-28 20:14
I'm working with a design that has the pagination in the header. This would be a great addition 👍

**Comment by adamsoffer** [comment] 2019-08-06 18:07
@mbrn - thank you for this awesome component! I was wondering - are there still plans to include this feature in a future release?

**Comment by baomastr** [comment] 2019-08-27 14:36
I've customized pagination position with cusom Pagination prop for `components`:

```javascript
  <MaterialTable
    components={{
      Pagination: props => {
        return (
          <td>
            <table
              style={{
                position: 'fixed',
                bottom: 0,
                left: 0,
                width: '100%',
              }}
            >
              <tbody>
                <tr>
                  <TablePagination {...props} />
                </tr>
              </tbody>
            </table>
          </td>
        );
      },
    }}
  />
```

additional table wrapper is for valid DOM nesting

**Comment by damienld22** [comment] 2020-01-31 16:29
Hello @mbrn,

First, thank you for your library, it is very useful for my projects !

I am very interested to have a property to set the position of the pagination. Is it possible to add the paginationPosition (top|bottom|both) property that you spoke ?

Thank you,


Damien

**Comment by shreya-shah** [comment] 2020-02-14 10:11
Hey @mbrn,

Thanks for providing such a great library.
It would be great if `pagination` component has a `position` property, which allows it to be placed either at the top or bottom of the table.
Looking forward to this feature.

Thanks,
Shreya

**Comment by mrjdavidfg** [comment] 2020-02-21 21:12
It would be even better if you could set pagination both at the top and bottom.

**Comment by stasbamiza** [comment] 2020-06-07 13:34
Hi!

I used DataTables for for old projects and I was wonder that I can change components positions. I tasted Material Table and it's nice lib. Unfortunately refused to use it. The main problem that I have design with different control position e.g. "Page Size selector" located over table in left side, "Pagination" with some changes located under table in right side, additionally have text "Show 10 records of 500" under table in left side. 

Conclusion: Guys you made good job, especially I like dynamic data loading(Ajax) but now I want as user Control current page, Pagination, Search query term etc. via props. I think that it allow us to implement hard design and create own controls with own control across props. 

Many thanks 😃

**Comment by iamsaurabhgupt** [comment] 2020-07-21 18:16
@mbrn we would like to move it to bottom centre.
This is a duplicate of my issue:
https://github.com/mbrn/material-table/issues/2131

**Comment by iamsaurabhgupt** [comment] 2020-07-21 18:17
See this image:
https://user-images.githubusercontent.com/43205009/86518555-e7ddfb80-be4f-11ea-9e7f-4f4e10585dc8.png

**Comment by macman2013** [comment] 2020-07-26 21:57
Hi,

I contributed this feature and it has been included as part of release [1.67.0](https://github.com/mbrn/material-table/releases/tag/v1.67.0). To use it, set the new `paginationPosition` prop to `top`, `bottom`, or `both`. The default pagination position is `bottom`. I hope everyone enjoys using this new option. Thanks!

**Comment by iamsaurabhgupt** [comment] 2020-07-27 05:19
@macman2013 how to move it to bottom center, as shown in my earlier comment?

**Comment by jpnuma** [comment] 2020-08-24 01:15
As a workaround, this can be done by CSS

`<MaterialTable
	style={{
		display: 'flex',
		flexDirection: 'column',
	}}`

Then on you css file:

`div.MuiToolbar-root { order: 1 }
div.MuiToolbar-root + div { order: 3 }
table.MuiTable-root { order: 2 }`

**Closed** 2020-11-29 02:04 UTC
Labels: enhancement, wontfix

**Comment by atinyakov** [comment] 2020-12-02 08:07
> Hi,
> 
> I contributed this feature and it has been included as part of release [1.67.0](https://github.com/mbrn/material-table/releases/tag/v1.67.0). To use it, set the new `paginationPosition` prop to `top`, `bottom`, or `both`. The default pagination position is `bottom`. I hope everyone enjoys using this new option. Thanks!

Hi, can you please update documentation on material-table.com, since this prop is not mentioned. Also, is `paginationPosition`  should be `<MaterialTable />` prop or `option prop` property?

**Comment by Mark-DSouza** [comment] 2021-02-28 05:31
> Hi @p34m5 ,
> 
> Thanks. Currently you can not. But i can add a option to paginationPosition (top|bottom|both) asap.

Could you update the docs to reflect this addition.

**Comment by KostasTur** [comment] 2022-03-24 07:34
To center the TablePagination component using styled api:

`const StyledTablePagination = styled(TablePagination)`
    .MuiTablePagination-toolbar {
      justify-content: center;
    }
    .MuiTablePagination-spacer {
      flex: none;
    }
  `

`

**Comment by AliMajedHA** [comment] 2023-07-10 18:42
Hello,
For the languages with a right-to-left layout, your component works great, except for the pagination layout.  I have read the documentation about localization, but I couldn't figure out how to style the pagination (bottom toolbar) correctly. The problem is for rtl layout, the order of the next page should be this: 
(next page <) (prev page >). 

The  only styles I could make are:
(next page >) (prev page <): The direction of the arrows is incorrect.
(prev page <) (next page >): the prev page and next page should be swapped.
