### ISSUE TITLE
Details dropdown spaced out too much with actions

### ISSUE THREAD

**Issue by jakeleventhal** [mbrn/material-table#1121] opened 2019-09-21 20:39 UTC
**Describe the bug**
If you have actions and a details panel, the dropdown for the details panel gets spaced out way too far. The details dropdown icon should be essentially right next to the actions buttons
<img width="544" alt="Screen Shot 2019-09-21 at 1 36 07 PM" src="https://user-images.githubusercontent.com/15133828/65378950-21ed6080-dc75-11e9-9b78-8bddcba4b2e3.png">

**To Reproduce**
Create a table with actions and a details panel.

**Expected behavior**
Icon should be next to the actions without giant space

**Screenshots**

**Comment by ingvaldlorentzen** [comment] 2020-02-19 15:56
I was experiencing a similar issue, but only when columns are hidden. I was not able to reproduce the issue without hidden columns, did you use hidden columns?

Anyways, I've fixed my issue in #1666

**Comment by jakeleventhal** [comment] 2020-07-05 20:10
not stale

**Comment by ingvaldlorentzen** [comment] 2020-07-05 20:15
> not stale

My fix has been merged. So this issue should be closed, no?

**Closed** 2020-07-07 03:29 UTC
Labels: bug, help wanted
