### ISSUE TITLE
Input fields added to overridden Toolbar loses focus on change

### ISSUE THREAD

**Issue by federico-bellucci** [mbrn/material-table#1047] opened 2019-08-29 09:32 UTC
**Describe the bug**
A TextField added to the Toolbar will lose focus on every keyboard event, hence it is unusable.

**To Reproduce**
1.Create a Material Table inside a function component
2. Override the Toolbar component and add a TextField
3. Control the TextField with `useState` (see live example)
4. Type inside the TextField to see that it loses focus on every key press

**Expected behavior**
TextField should not lose focus on every key press. 

**Live example**
https://codesandbox.io/embed/material-table-toolbar-overriding-2v6js

**Comment by dmyalik** [comment] 2019-09-03 23:00
Hi, I have had the same issue. Here is some details about it - [link ](https://github.com/mbrn/material-table/issues/523)
I have worked on a custom filter and wanted to display it in the toolbar, in the end, I have just moved this filter above the table and have a button to refresh a table data according to filter items.

**Comment by uccio83** [comment] 2019-09-06 09:51
Hi @dmyalik. Thank you for your reply. I've came to the same solution as you and I managed to arrange the CSS in order to show the input inside the table container. But it's an ugly workaround. I hope the maintainers will address soon this this issue.

**Comment by simromm** [comment] 2020-03-13 14:33
Any update?

**Comment by lillogoal** [comment] 2020-03-17 09:32
Any update ?

**Comment by smorstabilini** [comment] 2020-03-18 08:48
This is a duplicate of https://github.com/mbrn/material-table/issues/523.
The solution is to define a new component for the toolbar.

This issue can be closed.

**Closed** 2020-07-12 19:33 UTC
Labels: bug, wontfix
