### ISSUE TITLE
Performance blocker after a version 1.62.0 of material-table

### ISSUE THREAD

**Issue by LuisPinaSoares** [mbrn/material-table#2531] opened 2020-10-07 22:19 UTC
Hi,

This is not an easy issue.
I am using material-table extensively on my application.
I was having serious performance issues, to the extend of having 3 tables loaded on the view and the performance after a few clicks just killed the browser.

Started trying to understand the issue.
Still haven't fully isolated it but from what i have tested everything works well if i am using version 1.62.0 if i update to the latest version i have a serious memory leak on material-table appearing, from what i saw it as something to do with CSS calculation or something.

I haven't yet looked for the version where this behaviour starts happening nonetheless i can give you a glimpse of what appears in memory when it goes south, take a look at memory snapshot bellow, memory gets flooded with some CSS computation. 

@mbrn if you think it is of any value i can try and see in which version it started happening. I can replicate the issue easily on my application, not sure if it is that easy in a simple code sandbox.
Could be my error but i think not, i have been chasing this for a few days.

![image](https://user-images.githubusercontent.com/11969403/95393478-96cc2080-08f2-11eb-9bf1-7b4207cb21b6.png)

![image](https://user-images.githubusercontent.com/11969403/95393443-861baa80-08f2-11eb-886a-44a32d768b67.png)

**Comment by SamerAlsayegh** [comment] 2020-10-07 23:25
Might be addressed in #2514 but this is a temporary workaround until @mbrn or someone more familiar with the codebase is able to isolate the issue.

**Comment by LuisPinaSoares** [comment] 2020-10-08 09:29
Do you have any idea at which version started happening this issue, probably this would help to further isolate it.
Thanks for the tip!

**Comment by SamerAlsayegh** [comment] 2020-10-08 15:21
Might be solved in https://github.com/mbrn/material-table/pull/2510 and seems to be an issue all the way back to 1.0.68, but also there were other issues mentioned with bulk editing at those versions.

**Comment by LuisPinaSoares** [comment] 2020-10-08 15:31
Not sure if it solved... because i confirmed this behaviour in the latest which was 1.69.1

**Comment by minelminel** [comment] 2020-10-14 21:53
I too have been trying to chase down this behavior the past few days, can confirm that I arrived at exactly the same conclusion of some CSS calculation hanging. In my application the string `calc` to be evaluated was ~26MB

I am able to reliable reproduce the issue within my app, and I'll start on a sandbox which will hopefully demonstrate the behavior clearly.

(Same version, **1.69.1**)

**Comment by manubamba** [comment] 2020-10-18 16:22
Confirmed that the issue does not exist on 1.61.0

**Comment by thisismydesign** [comment] 2020-10-20 16:10
I have a similar issue with 1.69.1 that is not present 1.62.0: When clicking on an action there's a huge spike on CPU load and my app freezes.

**Comment by LuisPinaSoares** [comment] 2020-10-20 21:21
From my brute force tests it seems that the bug was added on 1.69.0.

**Comment by TimBenn** [comment] 2020-11-12 20:01
Same issue, currently (1.69.1) only on a table I have external custom filters. Huge cpu spike after switching quickly between filters. @SamerAlsayegh 's suggestion helped for now. Any updates?

**Comment by peacechen** [comment] 2021-01-08 14:22
Unfortunately mbrn is inactive and not merging PR's. Use the official community fork [@material-table/core ](https://github.com/material-table-core/core)instead.

**Comment by skulljoi** [comment] 2021-04-08 18:10
For me it's working again 1.69.2 with the last material-ui

**Comment by thisismydesign** [comment] 2021-07-07 20:57
Still relevant

**Comment by LuisPinaSoares** [comment] 2021-07-08 09:26
Check this fork of material-table https://www.npmjs.com/package/@material-table/core
Its under active maintenance and already has this issue fixed.

**Closed** 2021-10-14 08:33 UTC
Labels: bug, wontfix
