### ISSUE TITLE
Delete last row in a page of remote data causes "Maximum update depth exceeded"

### ISSUE THREAD

**Issue by perfectstrong** [mbrn/material-table#864] opened 2019-07-24 09:09 UTC
**Describe the bug**
A table to interact with data from remote source: create, update and delete.

**To Reproduce**
For example, with a pagination of 5 items per page for 6 items, clicking "delete" the 6th item (first row of 2nd page) will result massive errors (not mention tons of request GET to server).

Here is a portion of code:
````react
    onRowAdd = (newData: Object) =>
        new Promise((resolve, reject) =>
            ProtocolController
                .post(newData)
                .then(resolve)
                .catch(reject)
        );

    onRowDelete = (oldData: Protocol) =>
        new Promise((resolve, reject) =>
            ProtocolController
                .delete(oldData)
                .then(resolve)
                .catch(reject)
        );

    /**
     *
     * @param oldData before changes
     * @param newData oldData with changes applied, must have the same id, but no method preserved
     * @return {Promise<Protocol | never>} the newly version of entity
     */
    onRowUpdate = (newData: Object, oldData: Protocol) =>
        new Promise((resolve, reject) =>
            ProtocolController
                .patch(newData, oldData)
                .then(resolve)
                .catch(reject)
        );

    onDataQuery = query => new Promise((resolve, reject) =>
        ProtocolController
            .get(query)
            .then(res =>
                resolve({
                    data: res.array,
                    page: res.paging.pageIndex,
                    totalCount: res.paging.totalElements,
                }))
            .catch(reject)
    );

    render() {
        return (
            <MaterialTable
                columns={this.columns}
                data={this.onDataQuery}
                editable={{
                    onRowAdd: this.onRowAdd,
                    onRowDelete: this.onRowDelete,
                    onRowUpdate: this.onRowUpdate,
                }}
            />
        );
    }
````

**Expected behavior**
User should return the previous page.

**Screenshots**
![image](https://user-images.githubusercontent.com/23375518/61780305-95542c80-ae02-11e9-8aa2-9a075cc12096.png)
![image](https://user-images.githubusercontent.com/23375518/61780400-b9b00900-ae02-11e9-99fc-35439d4eb4f4.png)

**Desktop**
 - OS: Windows 10
 - Browser: Firefox
 - Package version: 1.40.1

**Comment by emrekara37** [comment] 2019-07-24 13:27
duplicate #537

**Comment by perfectstrong** [comment] 2019-07-24 13:56
I saw a recent correction here https://github.com/mbrn/material-table/pull/738 but that seems not working.

**Comment by jakecinco** [comment] 2019-10-25 11:56
@perfectstrong What's this ProtocolController, Protocol and Object in your code?

**Comment by jayarjo** [comment] 2019-10-25 12:13
Closing this as duplicate of another one, which now has been scheduled to be fixed in very next minor release.

**Closed by jayarjo** 2019-10-25 12:13 UTC
Labels: bug, duplicate
