### ISSUE TITLE
window is defined in next.js

### ISSUE THREAD

**Issue by sk1794** [mbrn/material-table#2155] opened 2020-07-10 14:14 UTC
I am getting error **widow not defined** in next.js after updating to v1.64.0, its because of jspdf You have used

**Comment by TaffarelXavier** [comment] 2020-07-12 01:20
I have same problem.

**Comment by floAr** [comment] 2020-07-12 19:44
This is related to #2112 and there is a pull request open already, in case you want to pluck the fix for yourself #2114 . The problem is withing jsPDF and the trick is to only import it if there is a window defined (which is not the case during server side render)

**Comment by Domino987** [comment] 2020-07-13 12:39
Closing in favor of #2112

**Closed by Domino987** 2020-07-13 12:39 UTC
Labels: bug

**Comment by yashas123** [comment] 2020-07-17 14:44
**Temporary fix is to use nextjs dynamic import:**
```js
import dynamic from "next/dynamic";

const MaterialTable = dynamic(() => import("material-table"), { ssr: false });
