### ISSUE TITLE
Make Material-UI a peer dependency?

### ISSUE THREAD

**Issue by oliviertassinari** [mbrn/material-table#472] opened 2019-04-16 13:54 UTC
What do you think of making Material-UI a peer dependency? You probably don't want people to bundle the library twice. It's what *notistack* and *material-ui-pickers* are doing.

**Comment by mbrn** [comment] 2019-04-16 18:32
Of course i can. Just one thing. It makes development harder, reason of npm install --no-save @mate... everytime dependencies updated. 

But i will do. I can change demo/test page as a another module by using lerna.

**Comment by oliviertassinari** [comment] 2019-04-16 19:16
@mbrn I'm not 💯 sure it's the right approach either. A few points to take into account:

- We should take https://bundlephobia.com/result?p=material-table into account. Something might be wrong with tree shaking, it's a different problem.
- Bundling multiple versions of Material-UI can create class name mismatches and bundle bloat.
- It makes installation more painful. It's true.

**Comment by eps1lon** [comment] 2019-05-14 11:40
Might be a good idea to specify the peer version of react as well.

**Comment by Foosballfan** [comment] 2019-05-30 12:50
Strongly in favour of this, will save ~300KB by not bundling material-ui twice.

**Comment by eps1lon** [comment] 2019-05-31 09:29
> Strongly in favour of this, will save ~300KB by not bundling material-ui twice.

@Foosballfan You should be able to avoud this by resolving duplicate entries of `@material-ui/core` in your lockfile. 

Bundling `@material-ui/core` twice can cause actual bugs (due to bundling `@material-ui/styles` twice).

**Comment by Foosballfan** [comment] 2019-05-31 09:45
@eps1lon So you mean remove this entry within material-table dependencies from the package-lock.json manually?
```
"@material-ui/core": {
          "version": "3.9.3",
          "resolved": "https://registry.npmjs.org/@material-ui/core/-/core-3.9.3.tgz",
          ...
}
```

**Comment by eps1lon** [comment] 2019-05-31 09:47
Only if they don't match i.e. if tables requires 3.x then you should also use 3.x. I can't give any guarantees that 3.x and 4.x in the same bundle works.

**Comment by Foosballfan** [comment] 2019-05-31 09:49
Ok great, I made sure they matched exactly in the hope that webpack would treeshake better so no problem there.

Feels like a dodgy fix to edit an auto generated file!

Thanks for the tip

**Comment by eps1lon** [comment] 2019-05-31 09:52
> Feels like a dodgy fix to edit an auto generated file!

Well flattening trees is pretty hard so yarn will occasionally miss some optimizations. `yarn check` can help detect those.

**Comment by ryancogswell** [comment] 2019-06-27 16:21
FYI -- someone encountering issues likely due to this (though they didn't provide a full reproduction of the problem so I can't be certain this is the cause):

https://stackoverflow.com/questions/56794892/material-table-styling-is-overiding-all-custom-and-material-ui-styling-and-icon

**Comment by ryancogswell** [comment] 2019-07-25 16:44
FYI -- another user encountering issues related to this:

https://stackoverflow.com/questions/57204404/adding-component-with-material-table-changes-material-ui-appbar-style

**Closed** 2020-06-30 18:08 UTC
Labels: enhancement, wontfix

**Comment by WalidKurchied** [comment] 2020-07-28 18:08
@oliviertassinari Any update on this ? Im currently working with multiple microprojects and was looking into a way to use material ui without bundling it in each project, My initial approach was to use the cdn version of material ui but if its possible to use peer dep that would be much better I'd say. Thank you.

**Comment by oliviertassinari** [comment] 2020-07-28 18:51
@WalidKurchied I don't have any specific update on this problem. The Material-UI team has its effort on the grid under https://github.com/mui-org/material-ui-x. We are working on an MIT and advanced enterprise data grid their.

**Comment by WalidKurchied** [comment] 2020-07-29 07:57
@oliviertassinari Thank you for letting me know.
