### ISSUE TITLE
CheckBox doesnt check when i use REACT HOOK  

### ISSUE THREAD

**Issue by aliburhankeskin** [mbrn/material-table#2411] opened 2020-09-03 18:49 UTC
I want to update checkBox status in  'onRowClick' event .  

```
1  const handleRowClick = (evt, rowData) => {
2    const rslts = data;
3    const index = rslts.indexOf(rowData);
4    rslts[index].tableData.checked = !rslts[index].tableData.checked;
5    setData(rslts); 
6
7   // Random state update
8    setRandom(!random);
9   };
```
When i  write code above it works but the application locked when i click repeatedly.

**Note:** Recommended solution for class component is code above except eighth line but i use function component.

Also if i remove  eighth line, the following bug is happening;

![2020-09-03-2145-55](https://user-images.githubusercontent.com/32386753/92155008-61ce3900-ee2f-11ea-91d0-5c742ce9bf21.gif)

Thanks for helping...

**Comment by Lalee10** [comment] 2020-09-08 06:05
This is not a bug with the table, this issue is with how you are setting state. Mutating the data and not assigning it a new reference before setting the state will result in React's reference check resulting in true and state not re-rendering.

Line 5: `setData([...rslts])` will update the state of your component and re-render the table as well since data has changed

**Closed** 2020-09-12 12:19 UTC
Labels: bug
